dotnet/tye

- docs/frontend_backend_run.md
Fixes a typo in the link of the documentation
> Fix typo in link

- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/Model/DockerRunInfo.cs
- src/Microsoft.Tye.Hosting/Model/ServiceDescription.cs
- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
- src/Microsoft.Tye.Hosting/TyeHost.cs
- src/tye/Program.RunCommand.cs
- test/E2ETest/TyeRunTests.cs
- This support builds the application locally then volume mounts the application into the container when the --docker flag is specified. Added support for volume mounts and working directory to the DockerRunner.
Here's what mult-project looks like with `tye run --docker`
> Add support for running local containers

- docs/frontend_backend_deploy.md
K3s seems like a good fit for people wanting to experiment with Tye.
> Add link to K3s

- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
- StaticAssets uses a physical path which doesn't work in the container without doing something crazy like rewriting the path. Instead, just publish the application before running it.
- This will prevent it from using relative paths for static assets
Found this while running @rynowak's application.
> Use dotnet publish to make static assets work

- restore.cmd
- restore.sh
Fixes https://github.com/dotnet/tye/issues/145
> Add restore files

- docs/frontend_backend_deploy.md
Changed the wording a little at the beginning that states that our tye app is already in containers. This isn't true, as the next step generates the images for the first time.
I'm not married to the new wording, feel free to suggest/edit if the voice is wrong.
> States we're already in containers, when we're not

- src/Microsoft.Tye.Hosting/TyeDashboardApi.cs
> renamed 'Metics' to 'Metrics'

- src/Microsoft.Tye.Core/ProcessUtil.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
- Make build errors show up in the output
> Make user secrets work in docker scenarios.

- docs/redis.md
- docs/schema.md
- samples/multi-project/tye.yaml
- src/tye/ConfigModel/ConfigApplication.cs
- src/tye/ConfigModel/ConfigService.cs
- Added a new image field and marked dockerImage as deprecated. Will remove in a future version.
- Fixes #122
> Renamed dockerImage to image

- src/Microsoft.Tye.Core/CombineStep.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- src/Microsoft.Tye.Hosting/ProxyService.cs
- src/Microsoft.Tye.Hosting/TyeDashboardApi.cs
- We inject ASPNETCORE_URLS, HTTPS_PORT and a PORTS env variable for binding.
> Clean up port injection

- docs/commandline/tye-run.md
- src/Microsoft.Tye.Core/StandardOptions.cs
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- src/Microsoft.Tye.Hosting/ProcessRunnerOptions.cs
- src/Microsoft.Tye.Hosting/TyeHost.cs
- src/tye/Program.RunCommand.cs
For part of https://github.com/dotnet/tye/issues/159
> Allow debugging specific projects

- docs/schema.md
- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/BindingBuilder.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigServiceBinding.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/Model/ServiceBinding.cs
- src/Microsoft.Tye.Hosting/Model/V1/V1ServiceBinding.cs
- src/Microsoft.Tye.Hosting/ProxyService.cs
- src/Microsoft.Tye.Hosting/TyeDashboardApi.cs
- src/tye/ApplicationBuilderExtensions.cs
> Rename internalPort to containerPort

- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- This lets ctrl+c work faster
> Delay instead of sleep with cancellation

- samples/voting/tye.yaml
- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigFactory.cs
- src/Microsoft.Tye.Hosting/HttpProxyService.cs
- If bindings are specified, add an http and https binding with autodetect port to true.
> Remove reading of launch settings

- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/Model/DockerStatus.cs
- src/Microsoft.Tye.Hosting/Model/V1/V1ReplicaStatus.cs
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- src/Microsoft.Tye.Hosting/TyeDashboardApi.cs
- Capture both stderr and stdout
- Run docker logs in a loop to capture the output for restarting containers.
Fixes #199
> Fixed capturing startup errors in containers and processes

- src/Microsoft.Tye.Hosting/Dashboard/Shared/MainLayout.razor
- src/Microsoft.Tye.Hosting/wwwroot/css/site.css
Current because the buttons are the same color as the background, it's kind of hard to see. 
I made the gray for now. feel free to suggest other colors instead.
> Make buttons pop a bit more

- .config/CredScanSuppressions.json
Cred scan error for internal builds
> Credential scans

- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/HttpProxyService.cs
- src/Microsoft.Tye.Hosting/Model/Service.cs
- src/Microsoft.Tye.Hosting/Model/ServiceBinding.cs
- src/Microsoft.Tye.Hosting/PortAssigner.cs
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- src/Microsoft.Tye.Hosting/ProxyService.cs
> Store data directly on the binding

- src/Microsoft.Tye.Hosting/ProcessRunner.cs
> Fix a *cool* policheck violation

- src/Microsoft.Tye.Core/DeployServiceYamlStep.cs
- src/Microsoft.Tye.Core/DockerfileGenerator.cs
- src/Microsoft.Tye.Core/ProcessUtil.cs
- src/Microsoft.Tye.Core/ValidateSecretStep.cs
- src/Microsoft.Tye.Hosting/Infrastructure/ProxyExtensions.cs
- src/tye/GenerateHost.cs
- src/tye/Program.DeployCommand.cs
i assume you would prefer to do dispose in an async manner where possible?
> do dispose async

- src/Microsoft.Tye.Hosting/Dashboard/Shared/MainLayout.razor
- src/Microsoft.Tye.Hosting/wwwroot/css/site.css
Nothing fancy, updated the UI colors for the dashboard. Thoughts??
> changed UI colors for dashboard

- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/DockerfileGenerator.cs
- src/Microsoft.Tye.Core/ProjectReader.cs
- src/Microsoft.Tye.Core/ProjectServiceBuilder.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/Model/ProjectRunInfo.cs
- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
- Improve ASP.NET project detection to work with netcoreapp2.1 applications
- Grab the target framework name and version from the project separately so we can use the vesion to determine the base image
- Updated Dockerfile generation and tye run --docker to work with different container versions based on the TFM version.
> Improve container base image detection

- src/Microsoft.Tye.Core/ConfigModel/ConfigFactory.cs
- src/Microsoft.Tye.Core/Serialization/OmitDefaultAndEmptyArrayObjectGraphVisitor.cs
- src/Microsoft.Tye.Core/Serialization/YamlSerializer.cs
- src/tye/InitHost.cs
- test/E2ETest/Infrastructure/StringExtensions.cs
- test/E2ETest/TyeGenerateTests.cs
- test/E2ETest/TyeInitTests.cs
Created a new object graph visitor for yaml dotnet to ignore default and also empty collections. Unifiy creation of serializer / deserializer well configured.
> Fix for issue #207

- src/Microsoft.Tye.Hosting/Model/Service.cs
> Lock around adding cached entries.

- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigVolume.cs
- src/Microsoft.Tye.Core/ProjectReader.cs
- src/Microsoft.Tye.Core/VolumeBuilder.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/Model/DockerRunInfo.cs
- src/Microsoft.Tye.Hosting/Model/DockerVolume.cs
- src/Microsoft.Tye.Hosting/Model/ProjectRunInfo.cs
- src/Microsoft.Tye.Hosting/Model/V1/V1DockerVolume.cs
- src/Microsoft.Tye.Hosting/Model/V1/V1RunInfo.cs
- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
- src/Microsoft.Tye.Hosting/TyeDashboardApi.cs
- src/tye/ApplicationBuilderExtensions.cs
- test/E2ETest/TyeRunTests.cs
- test/E2ETest/testassets/projects/volume-test/Program.cs
- test/E2ETest/testassets/projects/volume-test/Properties/launchSettings.json
- test/E2ETest/testassets/projects/volume-test/Startup.cs
- test/E2ETest/testassets/projects/volume-test/appsettings.Development.json
- test/E2ETest/testassets/projects/volume-test/appsettings.json
- test/E2ETest/testassets/projects/volume-test/tye.yaml
- test/E2ETest/testassets/projects/volume-test/volume-test.csproj
- Added tests
Contributes to #249
> Add support for named docker volumes

- src/Microsoft.Tye.Core/GenerateDockerfileStep.cs
> Revert changes to Dockerfile step

- src/Microsoft.Tye.Hosting/DockerImagePuller.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/TyeHost.cs
- This step also validates that docker is installed before trying to pull and before running so that logic can be removed from the DockerRunner.
- Let the application exit if it tye run fails to start.
Fixes #222
> Pull docker images before running

- src/Microsoft.Tye.Hosting/Dashboard/Pages/Index.razor
- src/Microsoft.Tye.Hosting/Dashboard/Pages/ServiceDetails.razor
- src/Microsoft.Tye.Hosting/Dashboard/Shared/MetricsDisplay.razor
- src/Microsoft.Tye.Hosting/Dashboard/Shared/ReplicaSelector.razor
- src/Microsoft.Tye.Hosting/Model/ReplicaStatus.cs
> Adds a very mad-katz metrics dashboard

- src/Microsoft.Tye.Core/ProjectReader.cs
- Ran into a strange case where some properties weren't being set (need to see if that means the right targets aren't running on the first pass). This was in a 2.1 application.
> Assume using the WebSDK means ASP.NET Core

- src/Microsoft.Tye.Hosting/Dashboard/Pages/_Host.cshtml
Fixes https://github.com/dotnet/tye/issues/14
I wanted to play with Tye and figured this was a quick fix to contribute ;).
I couldn't resist a little nerd jokery too, but I'm happy to edit it to be more "serious" if preferred:
> add a custom reconnect dialog

- docs/schema.md
- src/schema/tye-schema.json
> Update schema and docs to describe name as optional

- src/Microsoft.Tye.Core/ConfigModel/ConfigApplication.cs
- src/Microsoft.Tye.Core/CoreStrings.resx
- test/UnitTests/TyeDeserializationValidationTests.cs
Fixes https://github.com/dotnet/tye/issues/232
> More yaml verification for a few scenarios

- src/Microsoft.Tye.Hosting/ProcessRunner.cs
Fixes https://github.com/dotnet/tye/issues/248. Also should fix https://github.com/dotnet/tye/issues/303.
This will have an impact on execution times, but that's expected with this change.
I ran the TyeRunTests before and after:
Before:
After:
Execution times are definitely longer, especially for the FrontendProjectBackendDocker (33 vs 49 seconds). We will need to investigate better solutions.
> Build sequentially instead of in parallel.

- src/tye/GenerateHost.cs
- src/tye/Program.DeployCommand.cs
- src/tye/Program.RunCommand.cs
> Show some progress while we're loading tye.yaml

- src/Microsoft.Tye.Hosting/TyeHost.cs
- src/tye/Program.RunCommand.cs
- test/E2ETest/TyeRunTests.cs
added `--dashboard` to launch the dashboard on `run`
Test is also added but should likely comment this out due to the need for selenium at this point.
> add dashboard option to auto launch

- src/Microsoft.Tye.Core/Serialization/ConfigApplicationParser.cs
- test/UnitTests/TyeDeserializationTests.cs
Add support to deserialize network key at HandleConfigApplication method of ConfigApplicationParser
> Fix ConfigApplicationParser to support network deserialization

- src/Microsoft.Tye.Core/ConfigModel/ConfigApplication.cs
- test/UnitTests/TyeDeserializationValidationTests.cs
> Allow multiple null ports (it means autogenerate)

- eng/Signing.props
> Use 3rd party cert for System.Reactive

- test/E2ETest/testassets/projects/Directory.Build.props
- test/E2ETest/testassets/projects/multi-project/worker/QueueWorker.cs
Fixes: #100
Makes the sample/test more idiomatic and resiliant
> Make multi-project sample more resiliant

- src/tye/tye.csproj
Remove PackageVersion tag with specific version number from tye.csproj
> Remove PackageVersion tag with specific version number from tye.csproj

- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- Generate an msbuild project on the fly to build all projects described in `tye.yaml`.
Here's what we generate for the voting sample:
```xml
<Project DefaultTargets="Build">
<ItemGroup>
<ProjectGroup0 Include="C:\dev\git\tye\samples\voting\vote\vote.csproj" />
<ProjectGroup0 Include="C:\dev\git\tye\samples\voting\worker\worker.csproj" />
<ProjectGroup0 Include="C:\dev\git\tye\samples\voting\results\results.csproj" />
</ItemGroup>
<Target Name="Build">
<MsBuild Projects="@(ProjectGroup0)" Properties="" BuildInParallel="true" />
</Target>
</Project>
```
Fixes #389
> Support parallel building of projects in tye.yaml

- src/Microsoft.Tye.Core/KubernetesManifestGenerator.cs
- Treat / the same as empty string for ingress deployments
> Fix slash for ingress deployment

- eng/Generate-StatusReport.ps1
> Add status report generator

- src/Microsoft.Tye.Core/KubernetesManifestGenerator.cs
- src/Microsoft.Tye.Core/ValidateIngressStep.cs
- src/Microsoft.Tye.Core/ValidateSecretStep.cs
- src/tye/Program.UndeployCommand.cs
- src/tye/UndeployHost.cs
- Fix use of default namespace for tye undeploy
- Support --namespace for tye undeploy
- Make handling of --namespace consistent
> Various namespace fixups

- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/ConfigFileFinder.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigService.cs
- src/Microsoft.Tye.Core/DirectoryExtensions.cs
- src/Microsoft.Tye.Core/GitDetector.cs
- src/Microsoft.Tye.Core/Microsoft.Tye.Core.csproj
- src/Microsoft.Tye.Core/Serialization/ConfigServiceParser.cs
- src/Microsoft.Tye.Core/ServiceBuilder.cs
- src/Microsoft.Tye.Core/TempDirectory.cs
- src/Microsoft.Tye.Hosting/Microsoft.Tye.Hosting.csproj
- src/Microsoft.Tye.Hosting/ReplicaRegistry.cs
- src/shared/DirectoryExtensions.cs
- src/tye/CommonArguments.cs
- test/E2ETest/ApplicationFactoryTests.cs
- test/E2ETest/TyeRunTests.cs
- test/Test.Infrastructure/TestHelpers.cs
Follow up to #414. Now adds ability to have a URL to clone from. Also addresses feedback after PR.
> Allows cloning dependencies

- src/Microsoft.Tye.Hosting/Dashboard/Pages/Index.razor
- src/Microsoft.Tye.Hosting/wwwroot/css/site.css
Added _word-break_ to services table
Horizontal scrolling is my natural enemy 😅
Closes #382
> Add word-break to source-project column

- docs/reference/commandline/tye-deploy.md
- docs/reference/commandline/tye-undeploy.md
- docs/reference/schema.md
- src/schema/tye-schema.json
> Add documentation for namespace

- azure-pipelines.yml
- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigService.cs
- src/Microsoft.Tye.Core/ContainerServiceBuilder.cs
- src/Microsoft.Tye.Core/Serialization/ConfigServiceParser.cs
- src/Microsoft.Tye.Hosting/DockerImagePuller.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/Model/DockerRunInfo.cs
- src/tye/ApplicationBuilderExtensions.cs
- test/E2ETest/TyeRunTests.cs
- test/E2ETest/testassets/projects/dockerfile/backend/Dockerfile
- test/E2ETest/testassets/projects/dockerfile/backend/app.js
- test/E2ETest/testassets/projects/dockerfile/backend/package-lock.json
- test/E2ETest/testassets/projects/dockerfile/backend/package.json
- test/E2ETest/testassets/projects/dockerfile/frontend/Program.cs
- test/E2ETest/testassets/projects/dockerfile/frontend/Properties/launchSettings.json
- test/E2ETest/testassets/projects/dockerfile/frontend/Startup.cs
- test/E2ETest/testassets/projects/dockerfile/frontend/appsettings.Development.json
- test/E2ETest/testassets/projects/dockerfile/frontend/appsettings.json
- test/E2ETest/testassets/projects/dockerfile/frontend/frontend.csproj
- test/E2ETest/testassets/projects/dockerfile/tye.yaml
- test/Test.Infrastructure/SkipIfDockerNotRunningAttribute.cs
Fixes https://github.com/dotnet/tye/issues/146
I don't know if well get this into the next release (I'm reluctant to just because I haven't finished the tye deploy story). There are also some paper cuts that are going to make it hard for adoption, including not automatically allocating ports for docker projects (looking into this).
> Allow specifying docker file for tye run

- docs/reference/service_discovery.md
> Update service discovery doc tell the truth

- docs/reference/commandline/README.md
- docs/reference/commandline/tye-build.md
- docs/reference/commandline/tye-deploy.md
- docs/reference/commandline/tye-push.md
- docs/reference/commandline/tye-undeploy.md
> Update command docs

- docs/reference/schema.md
- src/schema/tye-schema.json
> Add ingress to docs

- docs/tutorials/hello-tye/01_deploy.md
- docs/tutorials/hello-tye/02_add_redis.md
> Mention undeploy in tutorial

- src/Microsoft.Tye.Core/PublishProjectStep.cs
Fixes #339 
`dotnet publish` logs to stdout instead of stderr with the error. Use ProcessUtils.RunAsync and log to the OutputContext instead.
We can also port other calls to do this as well.
> Log from stdout when dotnet publish fails

- docs/README.md
- docs/recipes/distributed_tracing.md
- docs/recipes/logging.md
- docs/reference/commandline/README.md
- docs/reference/commandline/tye-build.md
- docs/reference/commandline/tye-deploy.md
- docs/reference/commandline/tye-push.md
- docs/reference/commandline/tye-undeploy.md
- docs/reference/multirepo.md
- docs/reference/schema.md
- docs/reference/service_discovery.md
- docs/tutorials/hello-tye/01_deploy.md
- docs/tutorials/hello-tye/02_add_redis.md
- src/schema/tye-schema.json
Here's a staging PR for all of the docs changes we need to make for 0.2. This way we can go HAM on docs without updating the master versions until we're ready.
> Staging PR for docs updates

- docs/recipes/dapr.md
Small typo in command produces error
> Update dapr.md for small typo

- docs/reference/local_development.md
> Docs for specifying base image:tag

- src/Microsoft.Tye.Core/ApplicationExecutor.cs
- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/ApplyContainerDefaultsStep.cs
- src/Microsoft.Tye.Core/BuildDockerImageStep.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigApplication.cs
- src/Microsoft.Tye.Core/ContainerServiceBuilder.cs
- src/Microsoft.Tye.Core/DockerContainerBuilder.cs
- src/Microsoft.Tye.Core/DockerFileServiceBuilder.cs
- src/Microsoft.Tye.Core/DockerfileGenerator.cs
- src/Microsoft.Tye.Core/DotnetProjectServiceBuilder.cs
- src/Microsoft.Tye.Core/GenerateDockerfileStep.cs
- src/Microsoft.Tye.Core/GenerateHelmChartStep.cs
- src/Microsoft.Tye.Core/GenerateOamComponentStep.cs
- src/Microsoft.Tye.Core/HelmChartGenerator.cs
- src/Microsoft.Tye.Core/ProjectReader.cs
- src/Microsoft.Tye.Core/ProjectServiceBuilder.cs
- src/Microsoft.Tye.Core/PublishProjectStep.cs
- src/Microsoft.Tye.Core/PushDockerImageStep.cs
- src/Microsoft.Tye.Extensions/DiagnosticAgent.cs
- src/Microsoft.Tye.Extensions/Elastic/ElasticStackExtension.cs
- src/Microsoft.Tye.Extensions/Zipkin/ZipkinExtension.cs
- src/Microsoft.Tye.Hosting/Model/ProjectRunInfo.cs
- src/tye/ApplicationBuilderExtensions.cs
- test/E2ETest/Microsoft.Tye.E2ETests.csproj
- test/E2ETest/TyeGenerateTests.cs
- test/E2ETest/TyeRunTests.cs
- test/E2ETest/testassets/generate/dockerfile.yaml
Fixes https://github.com/dotnet/tye/issues/146
Adds a new type that represents a DockerFile (so it gets ports and stuff).
> Add docker file support for deploy 

- src/Microsoft.Tye.Core/CoreStrings.resx
Minor grammar correction, hopefully clear by itself.
Btw this project looks great, to me it's the most exciting of all recent .NET announcements so far.
> Correct grammar (Excpeted => Expected)

- docs/reference/schema.md
Azure Container Registry Login Server is usually the registry name + `azurecr.io`.
> Docs: Updated Container Registry Server example

- src/Microsoft.Tye.Hosting/HttpProxyService.cs
- test/E2ETest/TyeRunTests.cs
- test/E2ETest/testassets/projects/apps-with-ingress/ApplicationA/Startup.cs
- test/E2ETest/testassets/projects/apps-with-ingress/ApplicationB/Startup.cs
Query string wasn't passed through ingress
This PR fixes it.
> passing query string in ingress

- src/schema/tye-schema.json
Needed to duplicate validation for dockerFile and image.
Fixes https://github.com/dotnet/tye/issues/533
> Fix schema validation

- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
Fixes https://github.com/dotnet/tye/issues/531
> Prefer User Directory for Projects into containers

- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigFactory.cs
- src/Microsoft.Tye.Core/ConfigModel/NameInferer.cs
- src/Microsoft.Tye.Core/Microsoft.Tye.Core.csproj
- src/Microsoft.Tye.Core/Serialization/YamlParser.cs
- src/tye/InitHost.cs
- src/tye/UndeployHost.cs
Fixes https://github.com/dotnet/tye/issues/518
Fixes https://github.com/dotnet/tye/issues/532
Application name didn't have a default in these scenarios. I went ahead and added inferring the application name to many places.
Also verified that undeploy with a dockerfile works.
> Fix undeploy

- .github/workflows/format.yml
Updating workflow for correct versions and variables:
> Updating workflow

- src/Microsoft.Tye.Hosting/Model/Application.cs
- test/E2ETest/testassets/projects/health-checks/tye-liveness.yaml
- test/E2ETest/testassets/projects/health-checks/tye-none.yaml
- test/E2ETest/testassets/projects/health-checks/tye-proxy.yaml
- test/E2ETest/testassets/projects/health-checks/tye-readiness.yaml
Fixes https://github.com/dotnet/tye/issues/354.
Working on verifying this now.
> Fixing docker host default

- eng/Versions.props
This reverts commit 9acc53022348d98f043566346e380514d6ecf757.
For rerelease.
> Revert "0.3 -> 0.4"

- docs/getting_started.md
This should be 0.4 since we bumped the version
> Update CI build instructions to use 0.4

- src/Microsoft.Tye.Hosting/TyeHost.cs
Add log for when the application is stopping. Addresses #https://github.com/dotnet/tye/issues/560
> Add application stopping message

- src/Microsoft.Tye.Core/DockerDetector.cs
My docker CLI is insanely slow after an update, this timeouts the docker command after 10 seconds.
> Add a timeout to the docker command

- build.sh
- docs/developer_guide.md
Addresses https://github.com/dotnet/tye/issues/540
> Update developer guide

- samples/frontend-backend/frontend/Program.cs
- samples/frontend-backend/tye.yaml
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
> Fix some metric on dashboard

- samples/frontend-backend/backend/backend.csproj
- samples/frontend-backend/frontend/frontend.csproj
- src/Microsoft.Tye.Core/DockerfileGenerator.cs
Fixes https://github.com/dotnet/tye/issues/561
> Add support for 5.0 and change sample to 5.0

- src/Microsoft.Tye.Core/DeployApplicationKubernetesManifestStep.cs
- src/Microsoft.Tye.Core/ValidateIngressStep.cs
- src/shared/KubectlDetector.cs
- src/tye/Program.DeployCommand.cs
Fixes https://github.com/dotnet/tye/issues/436
> Add logging for KubectlDetector logic

- docs/reference/schema.md
- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigService.cs
- src/Microsoft.Tye.Core/Serialization/ConfigServiceParser.cs
- src/schema/tye-schema.json
Fixes https://github.com/dotnet/tye/issues/433
> Add clone directory

- src/Microsoft.Tye.Hosting.Diagnostics/DiagnosticsCollector.cs
Fixes https://github.com/dotnet/tye/issues/466
> Fix diagnostics collection logs

- src/Microsoft.Tye.Hosting/ProcessRunner.cs
Fixes https://github.com/dotnet/tye/issues/596.
There is still another underlying issue where because we call func with --build, it causes file conflicts. I'm going to look into this a bit.
> Copy args into func

- docs/tutorials/hello-tye/02_add_redis.md
Fix of the default directory name used in the examples
> Fix of the directory name

- CONTRIBUTING.md
Corrected a minor grammar issue and cleanup unneeded commas
> Fix minor grammar issue and cleanup commas

- src/Microsoft.Tye.Hosting/Watch/Internal/MsBuildFileSetFactory.cs
> quote project path to handle spaces.

- src/Microsoft.Tye.Core/ProjectReader.cs
- test/E2ETest/ApplicationFactoryTests.cs
- test/E2ETest/testassets/projects/frontend-backend/tye-wrong-projectpath.yaml
* Produce a useful error message if the path of a project file is incorrect in tye.yaml.
* Added a test.
> Fixed issue #620

- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/shared/DirectoryExtensions.cs
This should fix the ubuntu builds
> Fix quotations around working directory

- docs/recipes/azure_functions.md
- docs/reference/schema.md
- src/Microsoft.Tye.Hosting/FuncFinder.cs
Fixes https://github.com/dotnet/tye/issues/625
> Add more locations to find func

- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
Fixes https://github.com/dotnet/tye/issues/689
> Fix dapr paths

- docs/reference/commandline/tye-build.md
- docs/reference/commandline/tye-deploy.md
- docs/reference/commandline/tye-init.md
- docs/reference/commandline/tye-push.md
- docs/reference/commandline/tye-run.md
- docs/reference/commandline/tye-undeploy.md
Updating the cli documentation after 0.5 release.
> Update cli args documentation

- src/Microsoft.Tye.Core/ApplicationFactory.cs
Refactored ApplicationFactory.cs
Applied language features on file ApplicationFactory.cs
> Feature refactor core

- docs/reference/schema.md
- src/schema/tye-schema.json
Fixes https://github.com/dotnet/tye/issues/865
> Fixing documentation for preserving prefixes for ingress.

- docs/reference/service_discovery.md
Reading named binding took me quite some time to actually get it to working, I believe adding this line would help other readers save some time
> reading named binding

- src/Microsoft.Tye.Hosting/HttpProxyService.cs
- test/E2ETest/TyeRunTests.cs
- test/E2ETest/testassets/generate/apps-with-ingress.1.18.yaml
- test/E2ETest/testassets/generate/apps-with-ingress.1.19.yaml
- test/E2ETest/testassets/projects/apps-with-ingress/ApplicationA/Startup.cs
- test/E2ETest/testassets/projects/apps-with-ingress/tye.yaml
Addresses https://github.com/dotnet/tye/issues/877
> Fixing ingress for local rules

- docs/getting_started.md
- eng/Versions.props
Completed verification, I'll push the packages to nuget in a few.
> Update version to 0.7

- src/Microsoft.Tye.Core/ConfigModel/ConfigFactory.cs
Fixes https://github.com/dotnet/tye/issues/934
> Prefer tye yaml always

- eng/Signing.props
- src/Microsoft.Tye.Core/Microsoft.Tye.Core.csproj
- src/Microsoft.Tye.Hosting/Microsoft.Tye.Hosting.csproj
- src/tye/tye.csproj
Fixes https://github.com/dotnet/tye/issues/942.
Let's see if tests pass 😄
> Update version of k8s client

- src/Microsoft.Tye.Hosting/Watch/Internal/MsBuildFileSetFactory.cs
Fixes https://github.com/dotnet/tye/issues/978
> Add quotes around file list for watch

- docs/getting_started.md
- eng/Versions.props
> Next release - 0.7.0

- docs/getting_started.md
- eng/Versions.props
> Update docs for 0.8 release

- docs/getting_started.md
- eng/Versions.props
Prepare for the 0.9.0 release.
> Prepare for 0.9.0 release

- docs/getting_started.md
- eng/Versions.props
Prepare the main branch for the release - 0.10.0.
> Prepare the main branch for the release - 0.10.0.

- src/Microsoft.Tye.Hosting/Model/V1/V1Metric.cs
- src/Microsoft.Tye.Hosting/Model/V1/V1MetricMetadata.cs
- src/Microsoft.Tye.Hosting/Model/V1/V1ServiceMetrics.cs
- src/Microsoft.Tye.Hosting/TyeDashboardApi.cs
This PR resolves what we've discussed in issue #1108. What do you think?
> Add json format for metrics

- Directory.Build.props
> Add LICENSE.txt to NuGet packages.

- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
Only add ports with http and https protocol to ASPNETCORE_URLS
Resolves #379
> Only add ports with http and https protocol to ASPNETCORE_URLS

- eng/Signing.props
- src/Microsoft.Tye.Core/Microsoft.Tye.Core.csproj
- src/Microsoft.Tye.Hosting.Diagnostics/Logging/LogObject.cs
- src/Microsoft.Tye.Hosting.Diagnostics/Microsoft.Tye.Hosting.Diagnostics.csproj
- src/Microsoft.Tye.Hosting/Microsoft.Tye.Hosting.csproj
- src/tye/tye.csproj
- test/Test.Infrastructure/EqualityYamlNodeVisitor.cs
Attempts to pull forward a number of Tye dependencies, both because they're generally getting pretty stale, but also to address certain corporate governance issues.
Props to @Hylaean for also trying to solve this longstanding issue.
Related to #1215
Resolves #1196
> Pull Tye dependencies forward

- src/Microsoft.Tye.Core/ProcessUtil.cs
Avoids a race condition where the CLI utility method may attempt to consume the accumulated standard and error output while output is still being written.
Related to #1280.
> Synchronize output buffers

- docs/getting_started.md
- docs/recipes/githubactions_aks.md
- eng/Versions.props
Post-release updates of version numbers and installation instructions.
> Update version numbers and installation instructions.

- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
- test/E2ETest/TyeRunTests.cs
- test/E2ETest/testassets/projects/dotnet-env-vars/single-project.sln
- test/E2ETest/testassets/projects/dotnet-env-vars/test-project/Program.cs
- test/E2ETest/testassets/projects/dotnet-env-vars/test-project/Properties/launchSettings.json
- test/E2ETest/testassets/projects/dotnet-env-vars/test-project/Startup.cs
- test/E2ETest/testassets/projects/dotnet-env-vars/test-project/test-project.csproj
- test/E2ETest/testassets/projects/dotnet-env-vars/tye.yaml
> Dont overwrite dotnet env vars when transforming projects into containers

- src/Microsoft.Tye.Hosting/HttpProxyService.cs
- test/E2ETest/TyeRunTests.cs
- test/E2ETest/testassets/projects/apps-with-ingress/ApplicationA/Startup.cs
- We need to add the middleware
> Fix tye's proxy for websockets

- src/Microsoft.Tye.Hosting/HttpProxyService.cs
> Don't use cookies on the proxy, just pass through the cookie header

- src/Microsoft.Tye.Hosting/Infrastructure/ProxyExtensions.cs
This fixes (at least part of) #1507 
I took the code from Microsoft yarp project, I guess it would be a nice feature to use all proxy-features from that project someday in the future
> Fix http/2 cookies for 1.1 requests
