dotnet/tye

- docs/redis.md
This is no longer needed now that we're public.
> Remove access token from redis docs

- docs/frontend_backend_run.md
As-is, in Step 7 the new user is in their IDE and "run project" will not work through the normal means (GetUrl throws since configuration values aren't there). This change makes it explicit that the user needs to go back to the command line and run 'tye run'.
Which was a gotcha on my first time through.
> Making 'tye run' explicit at end of instructions

- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/Model/ProjectRunInfo.cs
- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
- src/tye/ConfigModel/ConfigApplication.cs
- src/tye/ConfigModel/ConfigService.cs
- src/tye/ConfigModel/ConfigVolume.cs
- src/tye/InitHost.cs
- src/tye/tye.csproj
- This also works when you run projects as containers.
```yaml
services:
- name: myservice
dockerImage: davidfowl/gohello
bindings:
- autoAssignPort: true
volumes:
- source: foo
target: /foo
```
Once we start using  the yaml reader, we can support the docker compose syntax as well (`{source}:{target}`)
> Added support for volume mapping docker containers

- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- This allows running executables that are on the path.
```yaml
services:
- name: myservice
executable: node
args: app.js
```
> Don't assume executables are relative to the context directory.

- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- Running a process starts a loop directly when starting up, instead of it should yield so that StartAsync can return.
> Allow shutting down even if startup fails.

- src/Microsoft.Tye.Core/ContainerInfo.cs
- src/Microsoft.Tye.Core/DeployServiceYamlStep.cs
- src/Microsoft.Tye.Core/DockerContainerBuilder.cs
- src/Microsoft.Tye.Core/DockerfileGenerator.cs
- src/Microsoft.Tye.Core/PublishProjectStep.cs
- src/Microsoft.Tye.Core/StandardOptions.cs
- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
- src/Microsoft.Tye.Hosting/TyeHost.cs
- src/tye/CommonArguments.cs
- src/tye/Program.BuildCommand.cs
Minor white-space, typo, structured logging, and consistent usage of 'Dockerfile' (and multi/single-phase) pass.
Also, addressed a couple typos in the CLI output in the help text.
> Minor white-space, typo, structured logging, and consistent usage of 'Dockerfile' changes

- src/Microsoft.Tye.Hosting/ProcessRunnerOptions.cs
- test/E2ETest/TyeRunTests.cs
Should have tested doing `tye run` without debugging projects. Whoops.
> Fix NullRef in Tye run when not specifying and projects to debug.

- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/ProjectReader.cs
- src/Microsoft.Tye.Core/ProjectServiceBuilder.cs
- src/Microsoft.Tye.Hosting/Dashboard/Pages/Index.razor
- src/Microsoft.Tye.Hosting/Model/ProjectRunInfo.cs
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
- src/Microsoft.Tye.Hosting/TyeDashboardApi.cs
- src/tye/ApplicationBuilderExtensions.cs
- This fixes several subtle bugs around how we resolve output paths adhoc and uses msbuild to find various outputs.
Fixes #184
> Use msbuild project info for running

- samples/multi-project/tye.yaml
- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Hosting/ProxyService.cs
Assume project ports are http by default but not container ports.
> Assume http only for projects, not containers

- src/Microsoft.Tye.Core/DockerContainerBuilder.cs
- src/Microsoft.Tye.Core/ProjectReader.cs
- src/Microsoft.Tye.Core/ProjectServiceBuilder.cs
- src/Microsoft.Tye.Core/PublishProjectStep.cs
- src/shared/TempDirectory.cs
- src/shared/TempFile.cs
- test/E2ETest/E2ETest.csproj
- test/E2ETest/TestHelpers.cs
- test/E2ETest/TyeBuildTests.Dockerfile.cs
- test/E2ETest/TyeBuildTests.cs
- test/E2ETest/TyeRunTests.cs
- test/E2ETest/testassets/projects/multi-phase-dockerfile/Program.cs
- test/E2ETest/testassets/projects/multi-phase-dockerfile/Properties/launchSettings.json
- test/E2ETest/testassets/projects/multi-phase-dockerfile/Startup.cs
- test/E2ETest/testassets/projects/multi-phase-dockerfile/appsettings.Development.json
- test/E2ETest/testassets/projects/multi-phase-dockerfile/appsettings.json
- test/E2ETest/testassets/projects/multi-phase-dockerfile/multi-phase-dockerfile.csproj
- test/E2ETest/testassets/projects/multi-phase-dockerfile/tye.yaml
- test/E2ETest/testassets/projects/single-phase-dockerfile/Dockerfile
- test/E2ETest/testassets/projects/single-phase-dockerfile/Program.cs
- test/E2ETest/testassets/projects/single-phase-dockerfile/Properties/launchSettings.json
- test/E2ETest/testassets/projects/single-phase-dockerfile/Startup.cs
- test/E2ETest/testassets/projects/single-phase-dockerfile/appsettings.Development.json
- test/E2ETest/testassets/projects/single-phase-dockerfile/appsettings.json
- test/E2ETest/testassets/projects/single-phase-dockerfile/single-phase-dockerfile.csproj
- test/E2ETest/testassets/projects/single-phase-dockerfile/tye.yaml
Fixes: #189
Fixes: #153
This change rejiggers the docker build infrastructure to publish the project
and generate a Dockerfile in the same directory. This way they can't be on
separate drives!
Also added some focused tests for single-phase docker build.
> Use same directory for Dockerfile and app

- samples/voting/tye.yaml
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- Adds auto assign port to the voting sample (was accidentally stashed when I was testing)
- Increase docker stop/remove timeouts and log a warning when we failed to timeout. I frequently hit the 5 second timeout locally, sometimes taking 5 to 10 seconds to stop docker.
> Two minor cleanup items

- docs/getting_started.md
- docs/schema.md
- src/schema/tye-schema.json
I made sure that tye run and tye deploy work, just in case. There a few bugs (https://github.com/dotnet/tye/issues/208, https://github.com/dotnet/tye/issues/205) that have already been fixed or have had docs that are updated that don't work against previous tye versions.
> Change version in getting_started for tye

- src/Microsoft.Tye.Hosting/TyeHost.cs
Add a CORS policy to MicronetesHost to allow discover backend service endpoints from a web frontend like a blazor webassembly or any javascript single page application.
In [Blorc.Core](https://github.com/WildGums/Blorc.Core) we have a configuration service that read values from configuration files that could be hosted in the web server.
_tye.development.json_
{
"Url": "http://127.0.0.1:5050"
}
We can specify the environment file with a parameter in the Url. In this case http://localhost:5005?env=development
So, the Program entry point could look like this:
var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("app");
builder.Services.AddBlorcCore();
if (await builder.IsTyeConfigurationAvailable())
{
builder.Services.AddSingleton<IServiceDiscovery, …
> Add a CORS policy to TypeHost

- src/Microsoft.Tye.Hosting/DockerRunner.cs
- test/E2ETest/TyeRunTests.cs
- Use the machine ip instead of host.docker.internal
PS: Will look into overwriting the host file in the container but its a tad bit hacky.
Fixes #176
> Work around host.docker.internal not working on linux

- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- We already set DOTNET_ENVIRONMENT which works on 3.0 and above apps but we also need to set ASPNETCORE_ENVIRONMENT for older apps.
Fixes #258
> Set ASPNETCORE_ENVIRONMENT to Development

- src/Microsoft.Tye.Core/Serialization/OmitDefaultAndEmptyArrayObjectGraphVisitor.cs
This is a minor perf tweek. but i figured it might be in the hot path, so i would submit it anyway
* combines an `is` and a cast into a pattern match
* which means the `value is object` should also be redundant?
* also the type param was never used
> optimise IsEmptyArray

- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/BindingBuilder.cs
- src/Microsoft.Tye.Core/CombineStep.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigIngressBinding.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigServiceBinding.cs
- src/Microsoft.Tye.Core/IngressBindingBuilder.cs
- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
- src/Microsoft.Tye.Hosting/Model/ServiceBinding.cs
- src/Microsoft.Tye.Hosting/PortAssigner.cs
- src/Microsoft.Tye.Hosting/TyeDashboardApi.cs
- src/tye/ApplicationBuilderExtensions.cs
- Make AutoAssignPort true by default for binding and ingress. If a binding is defined auto assign the port. This will of course be ignored if there's a port defined.
- Don't auto assign a port if it's there's a connection string defined.
Allows things like this:
```yaml
services:
- name: frontend
executable: node
args: frontend\app.js
bindings:
- protocol: http
- name: backend
executable: go
args: run backend\main.go
bindings:
- protocol: http
```
> Make ports go away

- test/E2ETest/TestHelpers.cs
- test/E2ETest/TyePurgeTests.cs
Note this is a breaking change. 
i cant tell if this is a bug in that it isnt used. or it is future proofing for when it will be needed?
> remove tyeDir from PurgeHostAndWaitForGivenReplicasToStop

- samples/dapr/tye.yaml
- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
It's against the law! using multiple replicas with dapr won't work correctly
with pub-sub until we add first-class sidecar handling to the hosting model.
This makes us fail with a reasonable error message for now.
> Ban replicas + dapr locally

- src/Microsoft.Tye.Hosting/ProcessRunner.cs
This PR adds passing of the project's directory to `dotnet build`.
This is required e.g. if the project contains a `global.json` file.
> Pass working directory to dotnet build

- src/Microsoft.Tye.Hosting/DockerImagePuller.cs
DockerImagePuller checks if the image is already installed before pull it
> DockerImagePuller checks the installed images first

- docs/redis.md
- samples/mongo-sample/tye.yaml
- samples/redis/tye.yaml
- src/Microsoft.Tye.Hosting/Dashboard/Pages/Index.razor
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/HttpProxyService.cs
- src/Microsoft.Tye.Hosting/Model/Application.cs
- src/Microsoft.Tye.Hosting/Model/DockerStatus.cs
- src/Microsoft.Tye.Hosting/Model/V1/V1ReplicaStatus.cs
- src/Microsoft.Tye.Hosting/PortAssigner.cs
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- src/Microsoft.Tye.Hosting/TyeDashboardApi.cs
- src/Microsoft.Tye.Hosting/TyeHost.cs
- src/tye/Program.RunCommand.cs
- test/E2ETest/TestHelpers.cs
- test/E2ETest/TyePurgeTests.cs
- test/E2ETest/TyeRunTests.cs
- This adds all containers in the tye.yaml to the same container network.
- Container networking only works with a single replica today since the containers are named after their replicas.
- Use the container host name and port when injecting env variables. This handles the multiple replica case by falling back to the host ip and port.
- This cleans up container to container communication when migrating docker-compose files.
- Don't override the container port if already set.
- Remove StopAsync from TyeHost and exposed DisposeAsync. This patterns removes common clean up and hanging issues that occur when errors happen on start/stop
- Cleaned up run tests to use similar code to run, clean up and capture logs.
> Add support for container networking

- samples/frontend-backend/frontend/ConfigurationExtensions.cs
- samples/frontend-backend/frontend/Startup.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/Model/Application.cs
- Turns out the same alias works fine and docker will
associate multiple IPs with a single alias
- Remove the docker run command from the output and leave it in the log
- Dump out the backend host names in the frontend backend example
Log clean up:
> We get proxying for free within the container

- docs/redis.md
- samples/Directory.Build.props
- samples/multi-project/backend/Program.cs
- samples/multi-project/backend/backend.csproj
- samples/multi-project/frontend/Program.cs
- samples/multi-project/frontend/frontend.csproj
- samples/multi-project/worker/Program.cs
- samples/multi-project/worker/worker.csproj
- samples/voting/vote/Program.cs
- samples/voting/vote/vote.csproj
- samples/voting/worker/Program.cs
- samples/voting/worker/worker.csproj
- src/Microsoft.Tye.Core/KubernetesManifestGenerator.cs
- src/Microsoft.Tye.Extensions.Configuration/Microsoft.Tye.Extensions.Configuration.csproj
- src/Microsoft.Tye.Extensions.Configuration/TyeSecretsConfigurationBuilderExtensions.cs
- src/Microsoft.Tye.Extensions.Configuration/TyeSecretsConfigurationSource.cs
- test/E2ETest/TestHelpers.cs
- test/E2ETest/TyeBuildTests.cs
- test/E2ETest/TyeGenerateTests.cs
- test/E2ETest/TyeInitTests.cs
- test/E2ETest/TyePurgeTests.cs
- test/E2ETest/TyeRunTests.cs
- test/E2ETest/testassets/generate/multi-project.yaml
- test/E2ETest/testassets/projects/Directory.Build.props
- tye.sln
This removes the need to copy-paste code that reads a specific directory
in Program.cs.
Updated docs/samples and tests.
We need a workaround in tests to be able to use a P2P for the library. What
I did here is the same trick we do in Razor.
- Force everyone to use an MSBuild variable to locate the library
- Set that variable in a Directory.Build.props for the normal build
- Drop a special Directory.Build.props for testing
Updates a bunch of test code to use new helper methods for copying
stuff, so we can correctly do this.
> Add a library for `AddTyeSecrets`

- samples/nginx-ingress/ApplicationA/ApplicationA.csproj
- samples/nginx-ingress/ApplicationA/Program.cs
- samples/nginx-ingress/ApplicationA/Properties/launchSettings.json
- samples/nginx-ingress/ApplicationA/Startup.cs
- samples/nginx-ingress/ApplicationA/appsettings.Development.json
- samples/nginx-ingress/ApplicationA/appsettings.json
- samples/nginx-ingress/ApplicationB/ApplicationB.csproj
- samples/nginx-ingress/ApplicationB/Program.cs
- samples/nginx-ingress/ApplicationB/Properties/launchSettings.json
- samples/nginx-ingress/ApplicationB/Startup.cs
- samples/nginx-ingress/ApplicationB/appsettings.Development.json
- samples/nginx-ingress/ApplicationB/appsettings.json
- samples/nginx-ingress/nginx-with-ingress.sln
- samples/nginx-ingress/nginx.conf
- samples/nginx-ingress/tye.yaml
- src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/Microsoft.Tye.Hosting.csproj
- src/Microsoft.Tye.Hosting/Model/Application.cs
- src/Microsoft.Tye.Hosting/Model/DockerRunInfo.cs
- src/Microsoft.Tye.Hosting/PortAssigner.cs
- src/Microsoft.Tye.Hosting/ProxyService.cs
- src/Microsoft.Tye.Hosting/TyeHost.cs
- src/Microsoft.Tye.Proxy/Microsoft.Tye.Proxy.csproj
- src/Microsoft.Tye.Proxy/Program.cs
- test/E2ETest/TyeRunTests.cs
- tye.sln
- This change introduces a container proxy which makes it possible for docker containers can talk to host services using container networking. These proxies will not show up in the dashboard as they are "infrastructure" containers.
- Added Private and NetworkAlias to DockerRunInfo but did not expose these configuration.
This is what the topology looks like:
Without replicas
With replicas
> Added container proxy for talking to the host

- activate.ps1
- activate.sh
So the idea here is that running `. .\activate.ps1` will also add a `dev-tye` function that automatically runs the `src\tye\tye.csproj` from the clone in which you ran `activate`. Because it's a global func, it works wherever you are. Running the `deactivate` function removes the `dev-tye` function.
Might be related to #262 ? @davidfowl had some comments there that seemed to be looking for more complicated stuff, but this seemed like something useful to me and might be nice for other folks in the repo.
I'm happy to just have this in my own scripts if people don't think this fits in the main `activate` script, or should be somewhere else. Just sketched it out while doing some exploration in teh repo and though it could be c o o l.
> Add 'dev-tye' func to `activate` scripts to improve local dev flow

- src/Microsoft.Tye.Core/ConfigModel/ConfigFactory.cs
- test/E2ETest/TyeInitTests.cs
- test/E2ETest/testassets/init/project-types.yaml
- test/E2ETest/testassets/projects/project-types/app/Program.cs
- test/E2ETest/testassets/projects/project-types/app/Properties/launchSettings.json
- test/E2ETest/testassets/projects/project-types/app/Startup.cs
- test/E2ETest/testassets/projects/project-types/app/app.csproj
- test/E2ETest/testassets/projects/project-types/app/appsettings.Development.json
- test/E2ETest/testassets/projects/project-types/app/appsettings.json
- test/E2ETest/testassets/projects/project-types/class-library/class-library.csproj
- test/E2ETest/testassets/projects/project-types/project-types.sln
- test/E2ETest/testassets/projects/project-types/test-project/UnitTest1.cs
- test/E2ETest/testassets/projects/project-types/test-project/test-project.csproj
Fixes: #206
This change only applies to the logic that we use to look at solution
files. This adds a heuristic that we only include projects with a
launchSettings.json for these operations (when considering a solution).
This will exclude unit test projects and class libraries.
In this case where the user has a `tye.yaml` then whatever's in there
will win. Likewise if a user passes a path to a project directly then
we'll try to run it without asking questions.
I chose `launchSettings.json` for this because it's a decision we can
make really quickly without having to run any MSBuild code. When we
think about operating on a solution with 50 projects with `tye run` we
really really don't want to have to evaluate each project with MSBuild
to figure out what kind of project it is (500ms).
> Exclude projects without launchSettings.json

- samples/dapr/orders/orders.csproj
- samples/dapr/products/products.csproj
- samples/dapr/store/store.csproj
- src/Microsoft.Tye.Hosting/Model/Application.cs
Fixes https://github.com/dotnet/tye/issues/285.
Having trouble running this locally at the moment due to the error:
```
"failed to start metrics server: listen tcp :49398: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
```
> Update dapr version

- src/Microsoft.Tye.Hosting.Diagnostics/DiagnosticsCollector.cs
For https://github.com/dotnet/tye/issues/212.
I think no matter what, there will be a race condition here at the moment. I have an idea about to actually fix this, but want to bounce this off people first.
The issue lies in the fact that the ProcessRunner is stopped before the EventPipeDiagnosticRunner: https://github.com/dotnet/tye/blob/master/src/Microsoft.Tye.Hosting/AggregateApplicationProcessor.cs#L35 (list is reversed, ProcessRunner is last in the list so it is first to shutdown). Now, in between the time where the StopAsync is called on the EventPipeDiagnosticRunner, the process has shutdown, which will restart the call to StartEventPipeSession, which will fail because the process shutdown.
@davidfowl do you think it's reasonable to move the EventPipeDiagnosticRunner after the …
> Don't log when pipe is broken

- src/Microsoft.Tye.Core/KubernetesManifestGenerator.cs
- test/E2ETest/testassets/generate/generate-connectionstring-dependency.yaml
Ran into during verification. connectionString vs connectionstring in kubernetes.
If we prefer connectionString, I can change the other place instead.
> connectionstring lowercase for kubernetes

- docs/tutorials/hello-tye/02_add_redis.md
Looks like the example redis deployment got moved to another part of the repo.
> Update link to redis manifest

- README.md
While Windows is case-insensitive, it appears GitHub nees the appropriate casing for the link to work.
> Correct FAQ link

- docs/tutorials/hello-tye/01_deploy.md
Changing yaml indentation of [01_deploy.md](https://github.com/dotnet/tye/blob/release/0.1/docs/tutorials/hello-tye/01_deploy.md)
from
```yaml
name: microservice
services:
- name: frontend
project: frontend/frontend.csproj
- name: backend
project: backend/backend.csproj
```
to
```yaml
name: microservice
services:
- name: frontend
project: frontend/frontend.csproj
- name: backend
project: backend/backend.csproj
```
> [DOCS] Align "project" and "name" nodes in 01_deploy.md of the default tye.yaml

- restore.cmd
In `dotnet/tye` the `restore.cmd` directly call `./eng/common/Build.ps1` (dotnet/arcade)  
It does try to call this script with `-all` and `-nobuild`
`./eng/common/Build.ps1` script does not have sutch switch `-all` or `-nobuild`
Original error :
After removing `-all` :
It seems that this logic was added to look like the one on `dotnet/aspnetcore`, the difference between both repository is that:
* dotnet/tye directly calls `./eng/common/Build.ps1` (no such switch)
* dotnet/aspnetcore calls first `./build.ps1` (the switch logic is in there), and later on call `./eng/common/Build.ps1`
TLDR :  Probably not important for now in this repo does not have (yet ?) any Node/Java Build to handle
After trying to understand the `build.ps1` at root level of `dotnet/aspnetcore`
here is what the `-all` …
> Restore.cmd fails on non-existing flags "-all" and "-nobuild"

- src/Microsoft.Tye.Hosting/ReplicaRegistry.cs
- We were passing the wrong file name to File.Delete
- Check for file existence before deletion as well.
Fixes #363
> Fixed issue with docker store deletion

- src/tye/Program.PushCommand.cs
- src/tye/Program.cs
This is what i'm using for #320
> Add push command

- docs/tutorials/hello-tye/01_deploy.md
People have been copying the entire content rather than just the registry, causing a parsing exception due to multiple names.
> Tye deploy nit

- docs/tutorials/hello-tye/02_add_redis.md
The second step of deploy already adds a registry, which we delete in this step.
> Add registry name to redis yaml

- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
- test/E2ETest/testassets/generate/dapr.yaml
- test/E2ETest/testassets/projects/dapr/tye.yaml
This PR adds `dapr.io/config` and `dapr.io/log-level` into the annotations section in dapr.yaml. Related to https://github.com/dotnet/tye/issues/296
> Add debug and tracing annotations

- samples/dapr/tye.yaml
- src/Microsoft.Tye.Core/ExtensionContext.cs
- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
- src/tye/ApplicationBuilderExtensions.cs
- src/tye/BuildHost.cs
- src/tye/GenerateHost.cs
- src/tye/Program.DeployCommand.cs
- src/tye/Program.PushCommand.cs
- src/tye/Program.RunCommand.cs
Fixes #296
Adds conditional logic for passing these properties to `daprd`.
Corrects logic for dealing with config. Dapr's config annotation in k8s
refers to kubernetes resource by name, but that's not possible with
local run. In local run `dapr` will expect the `-config` parameter to be
a file on disk. So, this change adds logic to look for a file by naming
convention and pass that locally instead.
Additionally added the ability for an extension to output to the console
- this is needed because we want to tell the user if their config file
can't be found, and specifically where we looked. I made the decision to
log a message and skip if the config file isn't present, because we
don't have a way to make settings conditional based on environment yet -
it makes sense that someone might need …
> Support dapr log level and config for local run

- src/Microsoft.Tye.Core/ProjectReader.cs
Fixes: #362
This change splits up our evaluation code-path into a few steps:
- Load project
- Do a restore
- Mark dirty
- Run targets and read properties
The key is that we need to do a restore separately from other targets
because restore will bring in nuget packages that contain targets. You
need to let MSBuild load those before continuing. The code here is
pretty similar to what dotnet does.
Additionally blocking the NBGV scenario, there are some additional
assemblies that need to be provided by MSBuild. NBGV also loads
Microsoft.DotNet.Platform.Abstractions which is part of the SDK. Since
we had an allow-list of just nuget assemblies that wasn't resolved.
> Address feedback about how we do evaluation

- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/ConfigModel/BuildProperty.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigService.cs
- src/Microsoft.Tye.Core/ProjectReader.cs
- src/Microsoft.Tye.Core/ProjectServiceBuilder.cs
- src/Microsoft.Tye.Core/Serialization/ConfigServiceParser.cs
- src/Microsoft.Tye.Hosting/Model/ProjectRunInfo.cs
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
- src/tye/tye.csproj
- test/E2ETest/E2ETest.csproj
- test/E2ETest/Infrastructure/ConditionalTheoryAttribute.cs
- test/E2ETest/Infrastructure/ConditionalTheoryDiscoverer.cs
- test/E2ETest/TyeRunTests.cs
- test/E2ETest/testassets/projects/frontend-backend/tye-debug-configuration.yaml
- test/E2ETest/testassets/projects/frontend-backend/tye-release-configuration.yaml
- test/UnitTests/TyeDeserializationTests.cs
Add buildProperties to project service configuration.
The service configuration could look like this:
...
services:
- name: projectA
project: ProjectA/ProjectA.csproj
buildProperties: 
- name: Configuration
value: Debug
> Add  buildProperties to project service configuration

- src/Microsoft.Tye.Core/ApplicationBuilder.cs
- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigApplication.cs
- src/Microsoft.Tye.Core/GenerateKubernetesManifestStep.cs
- src/Microsoft.Tye.Core/KubernetesManifestGenerator.cs
- src/Microsoft.Tye.Core/Serialization/ConfigApplicationParser.cs
- src/Microsoft.Tye.Core/StandardOptions.cs
- src/tye/GenerateHost.cs
- src/tye/Program.DeployCommand.cs
- src/tye/Program.GenerateCommand.cs
cc @davidfowl 
I monkey-patched the path from the CLI down into the generator. Let me know if there is a preferred path to pass this through.
> Add the ability to specify a namespace for tye deploy.

- test/E2ETest/TyeBuildTests.Dockerfile.cs
- test/E2ETest/TyeBuildTests.cs
- test/E2ETest/TyeGenerateTests.cs
- test/E2ETest/TyeInitTests.cs
- test/E2ETest/TyePurgeTests.cs
- test/E2ETest/TyeRunTests.cs
- test/Test.Infrastructure/ConditionalFactAttribute.cs
- test/Test.Infrastructure/ConditionalFactDiscoverer.cs
- test/Test.Infrastructure/ConditionalTheoryAttribute.cs
- test/Test.Infrastructure/ConditionalTheoryDiscoverer.cs
- test/Test.Infrastructure/DockerAssert.cs
- test/Test.Infrastructure/EqualityYamlNodeVisitor.cs
- test/Test.Infrastructure/ITestCondition.cs
- test/Test.Infrastructure/RetryHandler.cs
- test/Test.Infrastructure/SkipIfDockerNotRunningAttribute.cs
- test/Test.Infrastructure/SkipOnLinuxAttribute.cs
- test/Test.Infrastructure/SkippedTestCase.cs
- test/Test.Infrastructure/Test.Infrastructure.csproj
- test/Test.Infrastructure/TestHelpers.cs
- test/Test.Infrastructure/TestMethodExtensions.cs
- test/Test.Infrastructure/TestOutputLogEventSink.cs
- test/Test.Infrastructure/TyeAssert.cs
- test/Test.Infrastructure/YamlAssert.cs
- test/UnitTests/ApplicationFactoryTests.cs
- test/UnitTests/TyeDeserializationTests.cs
Spelling mistake in test infrastructure project and I forgot to update the namespace for the skip attributes
> Fix bad namespace changes in test projects

- docs/tutorials/hello-tye/00_run_locally.md
cc @davidfowl @jkotalik 
Partially addresses #367
> Improve docs somewhat.

- restore.sh
This script had some wrong arguments (bad copy-paste from a more
complex repo). The restore.cmd script already had this fixed.
> Fix restore.sh

- src/Microsoft.Tye.Core/DockerfileGenerator.cs
- Use the assembly name as the entrypoint instead of the project file name.
> Fix docker image building

- docs/README.md
- docs/recipes/distributed_tracing.md
- samples/frontend-backend/backend/Program.cs
- samples/frontend-backend/frontend/Program.cs
- src/Microsoft.Tye.Core/Extension.cs
- src/Microsoft.Tye.Core/ExtensionContext.cs
- src/Microsoft.Tye.Core/HostOptions.cs
- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
- src/Microsoft.Tye.Extensions/WellKnownExtensions.cs
- src/Microsoft.Tye.Extensions/Zipkin/ZipkinExtension.cs
- src/Microsoft.Tye.Hosting.Diagnostics/DiagnosticOptions.cs
- src/Microsoft.Tye.Hosting/HostOptions.cs
- src/Microsoft.Tye.Hosting/ProcessRunnerOptions.cs
- src/Microsoft.Tye.Hosting/TyeHost.cs
- src/tye/ApplicationBuilderExtensions.cs
- src/tye/BuildHost.cs
- src/tye/GenerateHost.cs
- src/tye/Program.DeployCommand.cs
- src/tye/Program.PushCommand.cs
- src/tye/Program.RunCommand.cs
- src/tye/Program.cs
- test/E2ETest/TyePurgeTests.cs
- test/E2ETest/TyeRunTests.cs
Adding a zipkin extension for local run (deployment is next).
This will automatically inject zipkin as a service to the application for local run. This also takes control of the `--dtrace` argument if not specified at the command line. 
Refactored how options get passed to the host, so that extensions can do stuff like this 👍 
```yaml
name: frontend-backend
extensions:
- name: zipkin
services:
- name: backend
project: backend/backend.csproj
- name: frontend
project: frontend/frontend.csproj
```
> Add distribute tracing recipe and extension

- NOTICE.txt
- eng/Signing.props
- src/Microsoft.Tye.Core/Microsoft.Tye.Core.csproj
- src/Microsoft.Tye.Core/ValidateIngressStep.cs
- src/Microsoft.Tye.Core/ValidateSecretStep.cs
- src/tye/UndeployHost.cs
Fixes https://github.com/dotnet/tye/issues/351.
I verified locally that having two kubeconfig files listed in the environment variable does not throw and returns an expected result.
> Update version of Kubernetes Client

- src/Microsoft.Tye.Core/ContainerServiceBuilder.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/Model/DockerRunInfo.cs
- src/Microsoft.Tye.Hosting/Model/EnvironmentVariable.cs
- src/Microsoft.Tye.Hosting/Model/ProjectRunInfo.cs
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
- src/tye/ApplicationBuilderExtensions.cs
- test/E2ETest/TyeRunTests.cs
- Support https properly inside of containers by injecting the dev cert into the right place.
- Only inject .NET specific environment for projects being transformed into containers.
- Use the same base image selection as deployment
- Added backoff to restarts
Fixes #267
> Fixes for docker scenarios

- src/Microsoft.Tye.Core/ConfigModel/ConfigFactory.cs
Fixes https://github.com/dotnet/tye/issues/345.
This just adds another check for <OutputType>exe</OutputType>. It's a pretty limited check.
> Check for output type exe

- src/Microsoft.Tye.Extensions.Configuration/Microsoft.Tye.Extensions.Configuration.csproj
- test/E2ETest/testassets/projects/multi-project/worker/Program.cs
Right now, if you target Microsoft.Tye.Extensions.Configuration, you'll get package downgrade warnings if you are targeting netcoreapp2.1.
> Target 2.1 for Microsoft.Extensions.Configuration

- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/tye/ApplicationBuilderExtensions.cs
- test/E2ETest/TyeRunTests.cs
Fixes #471 
From what I can tell, the issue is that docker build doesn't like providing an absolute path with a trailing slash.
> Trim trailing slash

- src/Microsoft.Tye.Hosting/Dashboard/Pages/Index.razor
Looking at https://github.com/dotnet/tye/issues/398 and noticed that we show a bunch of things that can never work for external.
```yaml
name: tyeweather
services:
- name: weather
project: weather/weather.csproj
env:
- name: API_KEY
value: <something>
- name: weatherext
external: true
bindings:
- protocol: https
port: 441
host: samples.openweathermap.orgz
```
Before:
After:
> Remove details for external services

- README.md
I think the Azure Devops badge should point to the public project
> Using public dnceng badge

- azure-pipelines.yml
Removing the steps that create AssetManifest files from Linux to prevent the Publish task from trying to upload the same assets multiple times in parallel and fail on file locks.
Removing empty parameter on macOS step.
> Fix dotnet feed publishing

- src/Microsoft.Tye.Hosting/DockerRunner.cs
- test/Test.Infrastructure/TestHelpers.cs
- Log the output to both the main window and the service logs when building.
- Make docker build cancellable (ctrl+c)
Fixes #491
> Small tweak to docker build

- docs/reference/commandline/tye-run.md
- src/Microsoft.Tye.Core/HostOptions.cs
- src/Microsoft.Tye.Hosting/TyeHost.cs
- src/tye/Program.RunCommand.cs
We allow the user to specify the level of output verbosity when running `tye run`
The levels are 
* **Debug** - display all logs
* **Info** (Default) - display only info (or warn/error) logs
* **Quiet** - display only warn/error logs
> log verbosity in tye run

- docs/recipes/probes.md
- docs/reference/schema.md
- samples/liveness-and-readiness/tye.yaml
- samples/liveness-and-readiness/webapi/Program.cs
- samples/liveness-and-readiness/webapi/Properties/launchSettings.json
- samples/liveness-and-readiness/webapi/Startup.cs
- samples/liveness-and-readiness/webapi/appsettings.Development.json
- samples/liveness-and-readiness/webapi/appsettings.json
- samples/liveness-and-readiness/webapi/webapi.csproj
- src/Microsoft.Tye.Core/ConfigModel/ConfigApplication.cs
- src/Microsoft.Tye.Hosting/ReplicaMonitor.cs
- test/UnitTests/TyeDeserializationTests.cs
- test/UnitTests/TyeDeserializationValidationTests.cs
* Expanded the `schema.md` document to contain `liveness` and `readiness` configuration
* Added a sample project and a recipe 
* Added basic deserialization and validation tests
* Changed some logs in `ReplicaMonitor` to debug, and some logs to information. 
About the last point, If service has liveness/readiness with `initialDelay` of zero, when running `tye run` you will see some warnings, because it takes time for the service to start accepting requests.  
This is okay since the fact that the default for `failureThreshold` is 3 (and the minimum is 1) accounts for it.  
Still, no reason to show warning logs so I've changed these logs to Debug, and other logs that the user should see, to Information. 
Problem is that `tye run` shows debug logs, and there is no way to control it. 
Should …
> Liveness and Readiness Documentation, Samples and Small Changes

- docs/reference/commandline/README.md
The commandline readme markdown file was pointing to a wrong link. Updated the link for Undeploy to point to the correct Tye-undeploy.md markdown file.
> Updated the reference to undeploy markdown file

- docs/recipes/probes.md
- samples/liveness-and-readiness/tye.yaml
- samples/liveness-and-readiness/webapi/HealthChecks.cs
- samples/liveness-and-readiness/webapi/Startup.cs
> using the ASP.NET Core HealthChecks library for the liveness/readiness sample

- docs/recipes/distributed_tracing.md
Fixing pointing to the public github url instead of raw content.
> Update documentation to fix kubectl apply command

- src/Microsoft.Tye.Core/ProcessSpec.cs
- src/Microsoft.Tye.Core/ProcessUtil.cs
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- src/Microsoft.Tye.Hosting/Watch/DotNetWatcher.cs
- test/E2ETest/TyeRunTests.cs
Prior, we would detect that the project needed to be rebuild, however we didn't actually rebuild the project as we just keep on running the executable. This was due to a bad refactor at the end of the feature.
> Actually call dotnet run with watch

- src/Microsoft.Tye.Core/DockerfileGenerator.cs
- test/E2ETest/testassets/generate/apps-with-ingress.yaml
- test/E2ETest/testassets/generate/dapr.yaml
- test/E2ETest/testassets/generate/dockerfile.yaml
- test/E2ETest/testassets/generate/frontend-backend.yaml
- test/E2ETest/testassets/generate/generate-connectionstring-dependency.yaml
- test/E2ETest/testassets/generate/generate-named-binding.yaml
- test/E2ETest/testassets/generate/generate-uri-dependency.yaml
- test/E2ETest/testassets/generate/health-checks.yaml
- test/E2ETest/testassets/generate/multi-project.yaml
- test/E2ETest/testassets/generate/multirepo.yaml
- test/E2ETest/testassets/generate/single-project-noregistry.yaml
- test/E2ETest/testassets/generate/single-project.yaml
> Removing color from deployed app console logs

- src/Microsoft.Tye.Hosting/ProcessRunner.cs
Fixes https://github.com/dotnet/tye/issues/527. WIP since I'm looking to add a test.
> Project with executable services only should launch

- src/Microsoft.Tye.Hosting/DockerRunner.cs
surrounded the volume statement with quotation marks so that spaces don't fail the run
> fix for bug #565

- samples/dapr/orders/orders.csproj
- samples/dapr/products/products.csproj
- samples/dapr/store/store.csproj
- samples/dapr/tye.yaml
- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
Add components-path to dapr extension to be able to change default dapr components-path. 
Closes #555
> supporting the components-path via dapr extension 

- samples/azure-functions/frontend-backend/README.md
- samples/azure-functions/typescript/README.md
- samples/azure-functions/voting/README.md
Small thing I noticed when doing verification.
> Update readme to specify that you may need a local.settings.json file for samples

- src/Microsoft.Tye.Hosting/Dashboard/Pages/Logs.razor
When doing `the run --watch` the other day we noticed you quickly ended up with a log full of stuff that could get in the way.
I threw a clear button onto my dashboard and thought I'd do a PR to discuss it. @JunTaoLuo seemed hesitant when we brought it up, did you want something that could clear the current screen and bring it back later if you cleared by mistake or something? Personally I think this seems fine as you aren't playing with prod logs, just try to debug problems.
I can style it better if we decide to merge it. Something that occurred to me as I thought about this was that perhaps we should have a collapsed checkbook list at the top that lets you select other services to display logs for. Like a poor mans/quick trace view without setting up proper distributed tracing. …
> Basic clear logs button

- docs/reference/commandline/tye-push.md
This file is "tye push", but a header text was "tye deploy".
> fix header typo

- docs/reference/service_discovery.md
Fix a couple of typos and add commas where needed in the service_discovery.md file
> Fix typos in service discovery document

- docs/recipes/dapr.md
high **never** of restarts -> high **number** of restarts
> fixed wording in doc dapr.md

- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
Fixes #635 
when exporting developer certificate from the Windows machine when the current logged in user's username contains space.
The submitted fix doesn't have a test. I'm not sure how to mock the environment to simulate a Windows machine with a space username.
> Wrap certificateFilePath with double quotation marks

- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
Found and fixed two more cases of commands executed with an unquoted file path leading to problems with spaces in the path (see issue #647). The following commands were fixed:
* Parameter working directory when calling docker run.
* Parameter clone directory when calling git clone.
> Fixed unquoted file paths

- src/Microsoft.Tye.Core/ProcessUtil.cs
Before this change, Tye would `CloseMainWindow` but that didn't have any effect because `CreateNoWindow` was set to `true` in the `ProcessStartInfo`. 
Now, when in Windows, I run the process with an invisible window and when I call `CloseMainWindow`, I wait 5 seconds for the process to exit gracefully (just like in Unix), before it's forcefully killed.
If `CloseMainWindow` fails (host can run from an environment where spawning windows is not possible), I default to killing the process (just like it has behaved before for Windows).
This solves a problem that I was having, I had an executable (parent) that launched another executable (child) and when Tye killed the parent, it would the child hanging.
> Graceful termination in Windows

- clean.cmd
- clean.ps1
- clean.sh
- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigService.cs
- src/Microsoft.Tye.Core/Microsoft.Tye.Core.csproj
- src/Microsoft.Tye.Core/ProjectReader.cs
- src/Microsoft.Tye.Extensions/Microsoft.Tye.Extensions.csproj
- src/Microsoft.Tye.Hosting.Diagnostics/Microsoft.Tye.Hosting.Diagnostics.csproj
- src/Microsoft.Tye.Hosting/Microsoft.Tye.Hosting.csproj
- src/tye-diag-agent/tye-diag-agent.csproj
- src/tye/ProjectEvaluation.targets
- src/tye/tye.csproj
- test/E2ETest/ApplicationFactoryTests.cs
- test/E2ETest/Microsoft.Tye.E2ETests.csproj
- test/Microsoft.Tye.Extensions.Configuration.Tests/Microsoft.Tye.Extensions.Configuration.Tests.csproj
- test/Test.Infrastructure/Test.Infrastructure.csproj
- test/UnitTests/Microsoft.Tye.UnitTests.csproj
Fixes https://github.com/dotnet/tye/issues/594
I have tested to ensure that the original issue where installing a 5.0 SDK would break apps has been fixed with this change. With this change, supporting new TFMs wouldn't require tye itself to be re-targeted.
So far testing the perf with frontend-backend sample gives:
Before:
backend.csproj
Evaluation Took: 1500.9242ms
frontend.csproj
Evaluation Took: 463.2118ms
After:
backend.csproj
Evaluation Took: 1733.3304ms
frontend.csproj
Evaluation Took: 1766.8971ms
So there is a performance penalty with running out of proc, especially with additional projects.
> Use out-of-proc MSBuild evaluation

- docs/reference/schema.md
- src/Microsoft.Tye.Core/CoreStrings.resx
- src/Microsoft.Tye.Core/Serialization/ConfigApplicationParser.cs
- src/Microsoft.Tye.Core/Serialization/ConfigServiceParser.cs
- src/Microsoft.Tye.Core/Serialization/YamlParser.cs
- test/UnitTests/Microsoft.Tye.UnitTests.csproj
- test/UnitTests/TyeDeserializationTests.cs
- test/UnitTests/testassets/envfile_a.env
- test/UnitTests/testassets/envfile_b.env
This PR addresses this issue https://github.com/dotnet/tye/issues/657
1. The `env` field in a service now accepts string of environment variables where the key and value are separated by a `=` sign.
2. If an element in `env` is either missing a `value` key or is a string that misses a `=` sign, the value of the environment variable is taken from the operating system/shell.
3. There is a new field under service, `env_file` which is a collection of strings which represent file paths. These file paths are formatted as explained in https://docs.docker.com/compose/env-file/
> Docker compose environment variable syntax

- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
Fixes: #575
Tye was missing code to set DAPR_HTTP_PORT when launching a project.
This variable is normally set by dapr when using `dapr run ...` to
launch a project. However Tye doesn't use `dapr run ...` so we need to
emulate this behavior.
We already had code to set up DAPR_GRPC_PORT which is used by the
`DaprClient` class. DAPR_HTTP_PORT is used by the actor runtime in
addition to behing available for arbitrary use (as reported in the
issue).
> Set DAPR_HTTP_PORT when launching project

- src/Microsoft.Tye.Core/ProjectReader.cs
Without this you get `Registered .NET SDK.Loading project...` with no space or line break between the two statements when verbosity is set to `Debug`.
> Add line break for better debug experience

- src/Microsoft.Tye.Core/DockerfileGenerator.cs
- src/Microsoft.Tye.Hosting/TransformProjectsIntoContainers.cs
- test/E2ETest/TyeRunTests.cs
- test/E2ETest/testassets/projects/single-project-5.0/single-project.sln
- test/E2ETest/testassets/projects/single-project-5.0/test-project/Program.cs
- test/E2ETest/testassets/projects/single-project-5.0/test-project/Startup.cs
- test/E2ETest/testassets/projects/single-project-5.0/test-project/appsettings.Development.json
- test/E2ETest/testassets/projects/single-project-5.0/test-project/appsettings.json
- test/E2ETest/testassets/projects/single-project-5.0/test-project/test-project.csproj
- test/E2ETest/testassets/projects/single-project-5.0/tye.yaml
Fixes https://github.com/dotnet/tye/issues/683. Note that the naming scheme is dependent on the TFM of the project: https://hub.docker.com/_/microsoft-dotnet-core
> Resolve base docker images correctly for .NET 5.0+ projects

- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/StandardOptions.cs
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
- src/tye/ApplicationBuilderExtensions.cs
- src/tye/ProjectEvaluation.targets
- test/E2ETest/ApplicationFactoryTests.cs
- test/E2ETest/TyeRunTests.cs
The main issue I hit during verification was that the override logic we had didn't work as intended.
Imagine the following scenario: 
1. The project is cross-targeting netcoreapp3.1 and net5.0
2. There is configuration in tye.yaml that specifies the TargetFramework to be net5.0
3. There is a command line argument --framework net3.1
Since we want to optimize evaluation speed, we opted for batching. Ideally, we would be able to send all the information, the TFM from tye.yaml and the hint from the command line, to MSBuild and have it sort out which TFM to restore/build for during project evaluation. 
However, I spent some time looking into the SDK and it looks like there's no chance for us to customize the logic. The SDK determines whether it's a cross-targeting build immediately when it's …
> Fix resolution of TFM overrides for multi-tfm projects

- src/Microsoft.Tye.Core/CombineStep.cs
- src/Microsoft.Tye.Core/KubernetesManifestGenerator.cs
fixes #725
It seems that the manifest code was mapping `binding.Port" to the field "containerPort" inthe  `KubernetesManifestGenerator`
As I have, for now, a limited understanding on that, There might be other underlying reason that I'm missing here
Adding back context from the Issue here for review:
From @jongio
https://github.com/dotnet/tye/issues/725#issuecomment-719975984
> Here's what I recommend:
> 
> If tye.yaml has containerPort, then use it for both containerPort in the deployment and targetPort in the service
> If tye.yaml doesn't have containerPort, then use 80 for http and 443 for https for both containerPort and targetPort.
> 
> I personally do not see a scenario where containerPort or targetPort should be equal to port
> 
> @jkotalik to confirm the logic above, but @tebeco …
> Map "binding.ContainerPort" instead of "binding.Port" to "manifest containerPort"

- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigIngressRule.cs
- src/Microsoft.Tye.Core/IngressRuleBuilder.cs
- src/Microsoft.Tye.Core/KubernetesManifestGenerator.cs
- src/Microsoft.Tye.Core/Serialization/ConfigIngressParser.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/HttpProxyService.cs
- src/Microsoft.Tye.Hosting/Model/IngressRule.cs
- src/schema/tye-schema.json
- src/tye/ApplicationBuilderExtensions.cs
Porting from https://github.com/dotnet/tye/pull/463. This will keep the path if a path is given for a particular redirect rule.
Fixes https://github.com/dotnet/tye/issues/729
> Adds preservePath for ingress

- src/Microsoft.Tye.Core/KubernetesManifestGenerator.cs
Small mistake in https://github.com/dotnet/tye/commit/df18a1d31bac543de05c498b1f2054031157a3c2, I forgot that we need to specify the path in the capture group.
> Fix nginx ingress path for capture group.

- samples/dapr/orders/Controllers/OrdersController.cs
- samples/dapr/orders/orders.csproj
- samples/dapr/products/products.csproj
- samples/dapr/store/Shared/ProductDisplay.razor
- samples/dapr/store/Startup.cs
- samples/dapr/store/store.csproj
Fixes https://github.com/dotnet/tye/issues/746
> Fixing dapr sample

- src/Microsoft.Tye.Core/StandardOptions.cs
- src/tye/Program.DefaultOptionsMiddleware.cs
- src/tye/Program.cs
- src/tye/StandardOptions.cs
- test/UnitTests/DefaultOptionsMiddlewareTests.cs
This is functionality which allows users to specify default options for commands in environment variables and this default options will be automatically applied.
More description with some examples is in #353.
> Added functionality to specify default options for commands

- src/Microsoft.Tye.Core/ProcessExtensions.cs
See the commits for more information
> Refactor core process extensions

- docs/reference/service_discovery.md
CONNECTIONSTRING comes as CONNECTIONSTRINGS in the environment variable.
(Discovery during debugging tye run --debug (code is .NET 5.0.100) via System.Environment.GetEnvironmentVariable
CONNECTIONSTRING__POSTGRES -> CONNECTIONSTRINGS__POSTGRES
> CONNECTIONSTRING comes as CONNECTIONSTRINGS

- docs/recipes/dapr.md
- samples/dapr/service-invocation/SentenceApp/SentenceApp.csproj
- samples/dapr/service-invocation/SentenceApp/Services/LowercaseServiceClient.cs
- samples/dapr/service-invocation/SentenceApp/Services/TitlecaseServiceClient.cs
- samples/dapr/service-invocation/SentenceApp/Services/UppercaseServiceClient.cs
This PR fixes some broken links in the Dapr recipe document and updates the service invocation sample to use the latest Dapr .NET SDK.
> Fix dapr recipe documentation and update sample to use latest .Net Dapr sdk

- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
- test/E2ETest/testassets/generate/dapr.yaml
Dapr v1.0.0-rc-1 introduced following [breaking change](https://github.com/dapr/dapr/blob/release-1.0/docs/release_notes/v1.0.0-rc.1.md#breaking-changes):
> The following annotations are no longer supported:
> 
> * `dapr.io/id`
> * `dapr.io/port`
> * `dapr.io/protocol`
> 
> Instead, use the following:
> 
> * `dapr.io/app-id`
> * `dapr.io/app-port`
> * `dapr.io/app-protocol`
This PR fixes the renamed annotations when deploying with Tye to k8s.
> adapt breaking changes of dapr 1.0.0.rc.1

- samples/dockercompose/ingress.yml
- src/Microsoft.Tye.Core/DeployApplicationKubernetesManifestStep.cs
- src/Microsoft.Tye.Core/KubernetesManifestGenerator.cs
- src/Microsoft.Tye.Core/ValidateIngressStep.cs
- test/E2ETest/testassets/generate/apps-with-ingress.yaml
I wanted to investigate the bugs I heard about ingress not working after an undeploy/deploy and look at reporting the ingress IPs after deploying with ingress. 
Running this code showed me that after deploying it can take a while to actually assign an IP. K8s docs say it can take "up to a minute or two". So I am thinking we want to wait for it to take and maybe show some progress when running in interactive mode. We can put it in here like I have but I was thinking it seems like it's time to add a `StatusStep` to the end of `DeployCommand.cs` that has a set of things we check on and report after deployment has happened.
What do you think?
> Improve nginx-ingress experience

- src/Microsoft.Tye.Core/ApplicationFactory.cs
Fixes https://github.com/dotnet/tye/issues/766. 
The issue is that if tye is installed in a directory path with spaces, such as when user profile contained spaces, the project evaluation command was broken. The fix is to add quotation marks around the path.
It's a bit hard to construct an unit test for this since tye needs to be installed in a special directory but I've verified this manually.
> Handle project evaluation target path with spaces

- src/Microsoft.Tye.Core/ProjectReader.cs
Addresses https://github.com/dotnet/tye/issues/516
Update the error message to be a little clearer where SDK resolution failed. For some added spiciness, I also changed the logic to resolve the SDK from the current working directory instead of the project directory. I think that better suits the principle of least surprise as suggested by the linked issue.
> Update SDK resolution and error message

- activate.ps1
- src/Microsoft.Tye.Core/ConfigFileFinder.cs
- src/tye/InitHost.cs
- test/E2ETest/TyeInitTests.cs
Addresses https://github.com/dotnet/tye/issues/894
Also fixes dtye to have arguments.
When we run tye init --force, if there is a present tye.yaml file, it will still be used as the slate for building the application model, rather than  other files like the sln or csproj that should be used. This reruns discovery on file types other than tye.yaml.
> Fix tye init --force

- src/Microsoft.Tye.Hosting/Infrastructure/ProxyExtensions.cs
Previously, Tye's ingress proxy wouldn't add X-Forwarded-* headers to its proxied requests, making anything which depends on the Host header for the request (e.g. OAuth redirect URIs, CORS origins, etc.) almost impossible. This PR adds those headers to proxied requests, so that reverse proxying more or less "just works" using more or less standard ASP.NET forwarded headers.
For example:
```cs
// ConfigureServices
services.Configure<ForwardedHeadersOptions>(options =>
{
options.ForwardedHeaders = ForwardedHeaders.All;
options.KnownProxies.Add(IPAddress.Loopback);
options.KnownProxies.Add(IPAddress.IPv6Loopback);
options.RequireHeaderSymmetry = true;
});
// Configure
app.UseForwardedHeaders();
```
I have not yet added these to proxied websocket requests, because I'm not 100% sure how …
> Add X-Forwarded-* headers for request proxying in ingress nodes

- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
Apparently it needs % encoded env vars, even on unix...
Verified on ubuntu.
> Fixing Env var for dapr on unix

- src/Microsoft.Tye.Core/ApplicationFactory.cs
This supersedes https://github.com/dotnet/tye/pull/827. Instead of throwing, log the failure at info level but keep the details at debug level.
> Log message at info level if project evaluation fails

- docs/recipes/ingress.md
I noticed some typo's while reading ingress.md and fixed them in this PR
> Fix some typos in ingress.md

- src/Microsoft.Tye.Core/ProcessUtil.cs
/cc @mikeharder who found the bug in crank
Some log might be lost because `WaitForExit()` is never called and the internal stdout/err buffers are not flushed.
> Flush  ProcessUtil buffer

- src/shared/KubectlDetector.cs
Resolves #927
Resolves #943
This PR updates Tye's KubectlDetector to handle plus signs in the minor version instead of returning an error message.
kubectl version -o json
```
{
"clientVersion": {
"major": "1",
"minor": "20",
"gitVersion": "v1.20.2",
"gitCommit": "faecb196815e248d3ecfb03c680a4507229c2a56",
"gitTreeState": "clean",
"buildDate": "2021-01-13T13:28:09Z",
"goVersion": "go1.15.5",
"compiler": "gc",
"platform": "linux/amd64"
},
"serverVersion": {
"major": "1",
"minor": "20+",
"gitVersion": "v1.20.1-34+e7db93d188d0d1",
"gitCommit": "e7db93d188d0d12f2fe5336d1b85cdb94cb909d3",
"gitTreeState": "clean",
"buildDate": "2021-01-11T23:50:46Z",
"goVersion": "go1.15.6",
"compiler": "gc",
"platform": "linux/amd64"
}
}
```
This line is the problem:
```
"minor": "20+",
```
> Handle plus signs in Kubernetes minor version

- docs/recipes/dapr.md
The Redis port is correct in the Dapr sample app, but it's incorrect in this recipe page.
> Recipes - fixed invalid port in Dapr sample code

- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
This PR:
- replaces the `daprd` startup with dapr CLI in order to have the `dapr dashboard` detect dapr services started with Tye as described in #965
> #965 change dapr startup from daprd to dapr CLI

- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
This PR:
- Is continued work on #965 
- Fixes the issues detected after merging #966 
- Fixes multiple args which are missing a `-` in their name
All affected arguments have been fixed to match the ones in `dapr run --help`
```
dapr --version
CLI version: 1.0.0
Runtime version: 1.0.1
dapr run --help
Run Dapr and (optionally) your application side by side. Supported platforms: Self-hosted
Usage:
dapr run [flags]
Examples:
dapr run --app-id myapp --app-port 5000 -- dotnet run
dapr run --app-id myapp -- java -jar myapp.jar
dapr run --app-id myapp --app-port 3000 -- node myapp.js
dapr run --app-id myapp -- python myapp.py
dapr run --app-id myapp
Flags:
-a, --app-id string                   The id for your application, used for service discovery
--app-max-concurrency int         The …
```
> Fixes to dapr.exe cmdline invocation

- src/Microsoft.Tye.Hosting/ProxyService.cs
Fixes https://github.com/dotnet/tye/issues/776
As we plan to remove bedrock.framework long term in favor of YARP, just going with the bandaid solution of catching the ODE from bedrock framework.
> Catch ODE from bedrock framework code

- docs/tutorials/hello-tye/01_deploy.md
I have added a small clarification right under the `deploy` command which can be useful for those who want to try `tye` and already have `kubectl` installed and that `kubectl` points to invalid context.
> Clarification of kubectl involvement in `deploy` command and potential error reason

- src/Microsoft.Tye.Core/ApplicationFactory.cs
With this fix, all variants should have been considered.
It was tested on a Windows system.
- Service without `cloneDirectory` property
- Service with absolute `cloneDirectory`property
- Service with relative `cloneDirectory`property
> Fix #901 - Executes git clone, based on the tye.yaml directory.

- src/Microsoft.Tye.Hosting/TyeDashboardApi.cs
Adds a dashboard "control plane" endpoint that allows shutting down the Tye application.
Related to #898.
> PoC Add "control plane" method to shutdown Tye application

- samples/dapr/pub-sub/orders/Startup.cs
- samples/dapr/pub-sub/orders/orders.csproj
- samples/dapr/pub-sub/products/products.csproj
- samples/dapr/pub-sub/store/store.csproj
- samples/dapr/service-invocation/SentenceApp/SentenceApp.csproj
- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
- src/Microsoft.Tye.Hosting/TyeHost.cs
General bug fixes I found when cleaning up tye for dapr samples and a cancellation on shutdown.
Fixes https://github.com/dotnet/tye/issues/1000 until `dapr run` is fixed to support placement port.
> Bunch of bug fixes for dapr support and fixing cancellation on stop async

- src/Microsoft.Tye.Hosting/DockerRunner.cs
For many use-cases there is no need to access the host.
> Don't consider it a fatal error when the container host is not accessible.

- src/Microsoft.Tye.Core/ApplicationFactory.cs
```
tye.exe run -v Debug
Loading Application Details...
Restoring and evaluating projects
Evaluating project failed with exit code 1
Ouptut: C:\Users\<User>\AppData\Local\Temp\....proj
```
> Fixing spelling in message seen with -v Debug

- src/Microsoft.Tye.Core/ConfigModel/ConfigApplication.cs
Fix copy-paste error in configuration validation process.
> fix configuration validation

- src/Microsoft.Tye.Hosting/Model/Application.cs
- src/Microsoft.Tye.Hosting/Model/V1/V1Application.cs
- src/Microsoft.Tye.Hosting/Model/V1/V1Control.cs
- src/Microsoft.Tye.Hosting/TyeDashboardApi.cs
- src/tye/ApplicationBuilderExtensions.cs
- test/Test.Infrastructure/TestHelpers.cs
Adds a `GET` `api/v1/control` endpoint that returns metadata related to the Tye application as a whole (vs. service-level metadata available via other endpoints). In particular, it returns an ID unique to the instance of Tye, the configured/inferred application name, and the source of the configuration (e.g. `tye.yaml` or a project file).
This metadata is helpful for tooling such as [`vscode-tye`](https://github.com/microsoft/vscode-tye), for example, to correlate applications back to a given workspace for debugging purposes.
Resolves #806
> Add endpoint for Tye application metadata

- docs/reference/schema.md
- src/schema/tye-schema.json
I had to dig a little bit to find out if it was possible to pass build arguments on a `tye.yaml` file. Turns out it is possible, it was made on #521, but I didn't find any docs explaining how. I just added a new section to the `schema.md`, let me know if there's anything I can add to make it more clear.
> Add dockerfile build args documentation

- src/Microsoft.Tye.Core/ExecutableServiceBuilder.cs
- src/Microsoft.Tye.Core/LaunchedServiceBuilder.cs
- src/Microsoft.Tye.Core/ProjectServiceBuilder.cs
- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
Currently only project-based services will have Dapr sidecars spun up when Dapr is enabled.  This prevents use of Dapr when using non-.NET-based services with Tye (e.g. Node.js or Python).  This change allows all executable-based services (with HTTP bindings) to have Dapr sidecars.
This change also has Tye use `dapr` for starting the sidecar rather than starting the sidecar (i.e. `daprd`) directly (which plays more nicely with how Dapr expects it to be started).
Resolves #1096.
> Allow executable-based services to have Dapr sidecars

- src/Microsoft.Tye.Core/ContainerEngine.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
> DockerRunner: podman workaround: create volume host dir when it doesn't exist.

- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/AzureFunctionServiceBuilder.cs
- src/Microsoft.Tye.Core/ContainerServiceBuilder.cs
- src/Microsoft.Tye.Core/DockerFileServiceBuilder.cs
- src/Microsoft.Tye.Core/DotnetProjectServiceBuilder.cs
- src/Microsoft.Tye.Core/ExecutableServiceBuilder.cs
- src/Microsoft.Tye.Core/ExternalServiceBuilder.cs
- src/Microsoft.Tye.Core/LaunchedServiceBuilder.cs
- src/Microsoft.Tye.Core/ProjectServiceBuilder.cs
- src/Microsoft.Tye.Core/ServiceBuilder.cs
- src/Microsoft.Tye.Core/ServiceSource.cs
- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
- src/Microsoft.Tye.Extensions/Elastic/ElasticStackExtension.cs
- src/Microsoft.Tye.Extensions/Seq/SeqExtensions.cs
- src/Microsoft.Tye.Extensions/Zipkin/ZipkinExtension.cs
- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/Model/Service.cs
- src/Microsoft.Tye.Hosting/Model/V1/V1Service.cs
- src/Microsoft.Tye.Hosting/TyeDashboardApi.cs
- src/tye/ApplicationBuilderExtensions.cs
- test/E2ETest/TyeRunTests.cs
Adds a `ServiceSource` property to service builders, which then gets propagated through the dashboard API service endpoints.
Resolves #1123.
> Track and report the "source" of a service.

- src/Microsoft.Tye.Core/ProcessUtil.cs
- test/E2ETest/ReplicaStoppingTests.cs
Because of the bug [dotnet/runtime#29232](https://github.com/dotnet/runtime/issues/29232), `process.WaitForExit()`
hangs for processes that spawn another long-running processes.
Since these are expected to be long-running processes and we're typically not concerned with capturing all of its output
i.e. it's probably ok for some output to be lost on shutdown since Tye is shutting down anyway, we added the timeout of 60 seconds to the `WaitForExit()` method so that we can shutdown the long-running processes.
Fixes #1128
> Add timeout for `Process.WaitForExit()`

- src/Microsoft.Tye.Hosting/Watch/DotNetWatcher.cs
This addresses #1138. I was unable to find a unit test for this change so let me know if you want one added or if one does exist and I would be happy to make any changes.
Before:
After:
> Improves error code log message in watch mode

- src/Microsoft.Tye.Hosting/TyeHost.cs
The tooling needs the `pid` of the application after it is started to match it to the applications the tooling has started and then execute operations on it (e.g. shutdown).
[microsoft/vscode-tye#127](https://github.com/microsoft/vscode-tye/issues/127) is such request from tooling where `pid` is required.
This PR adds a log to emit the `pid` after the application has started.
> Log the Pid after Tye application is started

- docs/reference/schema.md
- src/Microsoft.Tye.Core/ApplicationBuilder.cs
- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/ConfigModel/ConfigApplication.cs
- src/Microsoft.Tye.Core/Serialization/ConfigApplicationParser.cs
- src/Microsoft.Tye.Hosting/Model/Application.cs
- src/Microsoft.Tye.Hosting/TyeHost.cs
- src/schema/tye-schema.json
- src/tye/ApplicationBuilderExtensions.cs
- test/E2ETest/Microsoft.Tye.E2ETests.csproj
- test/E2ETest/TyeRunTests.cs
- test/E2ETest/testassets/projects/non-standard-dashboard-port-5.0/single-project.sln
- test/E2ETest/testassets/projects/non-standard-dashboard-port-5.0/test-project/Program.cs
- test/E2ETest/testassets/projects/non-standard-dashboard-port-5.0/test-project/Startup.cs
- test/E2ETest/testassets/projects/non-standard-dashboard-port-5.0/test-project/appsettings.Development.json
- test/E2ETest/testassets/projects/non-standard-dashboard-port-5.0/test-project/appsettings.json
- test/E2ETest/testassets/projects/non-standard-dashboard-port-5.0/test-project/test-project.csproj
- test/E2ETest/testassets/projects/non-standard-dashboard-port-5.0/tye.yaml
- test/E2ETest/testassets/projects/non-standard-dashboard-port/single-project.sln
- test/E2ETest/testassets/projects/non-standard-dashboard-port/test-project/Program.cs
- test/E2ETest/testassets/projects/non-standard-dashboard-port/test-project/Properties/launchSettings.json
- test/E2ETest/testassets/projects/non-standard-dashboard-port/test-project/Startup.cs
- test/E2ETest/testassets/projects/non-standard-dashboard-port/test-project/appsettings.Development.json
- test/E2ETest/testassets/projects/non-standard-dashboard-port/test-project/appsettings.json
- test/E2ETest/testassets/projects/non-standard-dashboard-port/test-project/test-project.csproj
- test/E2ETest/testassets/projects/non-standard-dashboard-port/tye.yaml
- test/Test.Infrastructure/TestHelpers.cs
Feature implementation for #1158 
It is a relatively small, and self-contained change with tests added, but I understand if it isn't something you want implemented in this project!  Submitting this PR to further discussion in the #1158 issue.
Thank again for everything, I've reaally enjoyed using Tye over the past six months or so.
> #1158 Feature/dashboard port in tye yaml

- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/AzureFunctionServiceBuilder.cs
- src/tye/ApplicationBuilderExtensions.cs
This PR is in relation to issue #1161 for supporting environment variables in Azure Functions. This was functionality that I was looking for and the schema shows that this should be supported. I've made a small change to allow this to work.
> Added support for environment variables when using Azure Functions

- samples/dapr/pub-sub/tye.yaml
- samples/dapr/service-invocation/tye.yaml
- src/Microsoft.Tye.Core/ProcessExtensions.cs
- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
Gets Tye out of the business of creating Dapr placement services, as most applications can use the one provided by the standard Dapr initialization (e.g. via `dapr init`) and that's what `dapr` assumes when running sidecars unless otherwise directed.  (If no placement service was running, just spinning one up as Tye was previously doing isn't sufficient due to dependencies on a properly configured state store.) Maintains the ability to have Dapr sidecars use a different port via `placement-port`.  The Dapr extension will check whether Dapr has been initialized (e.g. via `dapr --version`) and fails if not, as a further hint to the user that something is amiss.
> NOTE: The placement service is required *only* for applications using Dapr actors. Applications using other Dapr features need …
> Removes Dapr placement server management

- docs/reference/schema.md
- src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs
- src/Microsoft.Tye.Extensions/Dapr/DaprExtensionConfiguration.cs
- src/Microsoft.Tye.Extensions/Dapr/DaprExtensionConfigurationReader.cs
Adds support for all of the various `dapr run` properties to be set/overridden in the `tye.yaml`.  (Previously only a few properties could be set, and not all could be overridden.)
Resolves #995.
Resolves #1174.
Resolves #1206.
Related to #1195.
> Support additional Dapr configuration properties

- docs/getting_started.md
Add more context around the .NET versions required and installation instructions for Tye.
Related to #1213
> Tweak confusing directions for Tye installations.

- src/Microsoft.Tye.Core/ProcessExtensions.cs
- src/Microsoft.Tye.Core/ProcessUtil.cs
Set `entireProcessTree` to `true` when killing processes to ensure we get the `daprd` child processes as well as its parent `dapr` process when shutting down an application.
Resolves #1231
> Generally kill both parent and their child processes.

- src/Microsoft.Tye.Core/ProjectReader.cs
Probably just a copy/paste typo. Spotted it coincidentally while browsing the code.
> Fix wrong variable in null check

- src/Microsoft.Tye.Hosting/DockerRunner.cs
- src/Microsoft.Tye.Hosting/ProcessRunner.cs
When setting ASPNETCORE_URLS env variable in ProcessRunner. This makes it possible to override which interface to bind to and also allow connections from anywhere by using a wildcard.
This is only tested for services configured as projects. Not sure how this affects other aspects of Tye.
Fixes #721
> Respect configured host in bindings

- src/Microsoft.Tye.Hosting/Watch/Internal/MsBuildFileSetFactory.cs
- Since the path is passed as a command-line parameter to dotnet, it needs to be enclosed in quotation marks in case it contains a space.
Resolves #1091.
> #1091 Quote path to DotNetWatch.targets

- install-tye.cmd
- install-tye.ps1
- install-tye.sh
- remove-tye.cmd
- remove-tye.sh
- src/Microsoft.Tye.Core/ApplicationFactory.cs
- src/Microsoft.Tye.Core/AzureFunctionServiceBuilder.cs
- src/Microsoft.Tye.Core/ProjectReader.cs
- src/Microsoft.Tye.Hosting/FuncFinder.cs
- src/Microsoft.Tye.Hosting/Model/AzureFunctionRunInfo.cs
- src/tye/ProjectEvaluation.targets
Updates the way in which we locate an Azure Functions runtime. Previously, this was hardcoded to version 3.  With this change, Tye will attempt to extract the `AzureFunctionsVersion` from the project file (assuming a .NET-based function), then using that to locate the proper runtime.  If no project or property was found, then Tye falls back to version 4.
Tye will now also use the host `func` executable to start the Azure Functions runtime, where previously it has executed the `func.dll` directly.  (For version 4, this method of starting the runtime no longer works.)
Resolves #1241.
> Also adds Tye installation/uninstallation scripts to eliminate having to remember/type the (often version-specific) commands.
> Add support for Azure Functions v4

- azure-pipelines.yml
These don't contribute official artifacts and otherwise would need to switch to 1ES pools.
> Don't run Mac/Linux in official build

- src/Microsoft.Tye.Hosting/Model/Application.cs
Some service configurations require the entire service endpoint (i.e. protocol/host/port) but don't have a mechanism to combine existing values provided through separate environment variables.  This change adds a `<service name>_SERVICE_ENDPOINT` environment variable for each service that contains its full endpoint.
> Set environment variable for entire service endpoint.

- src/Microsoft.Tye.Core/PublishProjectStep.cs
Based on the current implementations `/nologo` will be used instead of `--nologo` as listed in the CLI Help.
Fix #1294
> Added missing parameter `/nologo` for `dotnet publish`

- samples/mongo-sample/tye.yaml
Looks like a copy paste error.  The `mongo` image uses different env variables.
> Fix mongo ENV variables

- docs/tutorials/hello-tye/00_run_locally.md
I removed two unneeded references from WeatherClient.cs
The instructions generate code in the new format, which results in only a `Program.cs` file needing the following code:
```
var builder = WebApplication.CreateBuilder(args);
// Add services to the container.
builder.Services.AddRazorPages();
builder.Services.AddHttpClient<frontend.WeatherClient>(client =>
{
client.BaseAddress = builder.Configuration.GetServiceUri("backend");
});
var app = builder.Build();
// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
app.UseExceptionHandler("/Error");
// The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
app.UseHsts();
}
app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting(); …
```
> Remove unneeded references, use code for .NET 6

- src/Microsoft.Tye.Core/Serialization/ConfigServiceParser.cs
I found this error while trying to use liveness and readiness health checks
If I try to use an Grpc service with liveness and readiness then it all breaks because it has to be https
(still doesn't work because Grpc uses HTTP/2 and I think that liveness and readiness ReplicaMonitor httpclient is using HttpVersion.Version11) :/
> Fix httpprobe protocol

- azure-pipelines.yml
The currently used ones have been replaced and any PR should fail without this change.
> Update windows ci image names

- docs/recipes/dapr.md
I had to go spelunking to understand how to configure individual services Dapr arguments and finally stumbled across it.  In addition, while specifying a custom components path was available in some documentation somewhere, it seems helpful to have it sit alongside the documentation on how to include the Dapr extension.
I'd be happy to include a list of the arguments if that would be useful but didn't want the documentation to get out of sync with the code that reads the Dapr extension configuration.
> Document options for configuring Dapr command args

- src/Microsoft.Tye.Core/MsBuild/ProjectInSolution.cs
- src/Microsoft.Tye.Hosting/BuildWatcher.cs
Provide the unique project name to the `-target` flag when doing an `msbuild <solution> -target:{unique project name}`.
Not only resolves the special characters but allows for the potential path in the "unique project name" (e.g., if your project is nested in a directory).
This addresses:
#1438 
Reference:
https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-build-specific-targets-in-solutions-by-using-msbuild-exe?view=vs-2022
> Allow for Special Characters in Project Names when Building During Watch

- src/Microsoft.Tye.Core/CoreStrings.resx
- src/Microsoft.Tye.Core/Serialization/TyeYamlException.cs
- src/Microsoft.Tye.Core/Serialization/YamlParser.cs
- test/UnitTests/TyeDeserializationValidationTests.cs
leverage file info when available, otherwise use more generic 'YAML file' phrasing
> remove 'tye.yaml' verbiage for YAML errors (#1033)

- src/Microsoft.Tye.Core/DeployApplicationKubernetesManifestStep.cs
- src/Microsoft.Tye.Core/ValidateSecretStep.cs
Also fixing error when successfully created ingress warned as non-created because of looking into wrong Kubernetes namespace.
Fixes https://github.com/dotnet/tye/issues/677
> Fixed issue #677 Secrets are not created on AKS non-default namespaces

- src/Microsoft.Tye.Extensions/Dapr/DaprExtensionConfigurationReader.cs
Fix Dapr extension services name not matching issue,  Applications services name changed from capital letters to lower-case
> Fix Dapr extension services name not matching
